### ISSUE TITLE
Cannot found nn_init

### ISSUE THREAD

**Issue by xingyun86** [nanomsg/nanomsg#1008]
Why I cannot found nn_init() in latest version?

**Comment by gdamore** [comment]
You should not ever need to call nn_init().  In fact, looking at the code, it can probably be removed from the library too, as I don't think anything is actually calling it.  It should only be used if you need to recover after calling nn_term().  And really, you should never call nn_term() unless you need to unload a shared library.  (A very very rare use case.)

This looks like something I added with an intention of documenting, but it never got documented, and I really would rather you didn't use this (or nn_term) unless you *absolutely* need to because you need this code to work in the context of an unloaded shared library.

(Let me know if you have other use cases for this that I've not thought of.)

**Comment by gdamore** [comment]
Anyway, nn_init() was never documented, and is not part of any promised API.  Closing.
