### ISSUE TITLE
replace thread with boost::fiber then not work

### ISSUE THREAD

**Issue by webbery** [nanomsg/nanomsg#1010]
Hi,
I write a simple test like this:  
```
//typedef std::thread WorkerType;
//#define SleepFor(x) std::this_thread::sleep_for(std::chrono::seconds(x))
typedef boost::fibers::fiber WorkerType;
#define SleepFor(x) boost::this_fiber::sleep_for(std::chrono::seconds(x))

#define LISTEN_POINT "inproc://test"

void pub() {
    int pb = nn_socket(AF_SP, NN_PUB);
    nn_bind(pb, LISTEN_POINT);
    while (1) {
        SleepFor(1);
        nn_send(pb, "1", 2, NN_DONTWAIT);
        std::cout << "send" << std::endl;
    }
}

void sub() {
    int sb = nn_socket(AF_SP, NN_SUB);
    nn_setsockopt(sb, NN_SUB, NN_SUB_SUBSCRIBE, "1", 1);
    nn_connect(sb, LISTEN_POINT);
    nn_pollfd pfd[1] = {
        {sb,NN_POLLIN ,0}
    };
    while (true) {
        int rc = nn_poll(pfd, 1, 20);
        if (rc == 0) continue;
        if (pfd[0].revents & NN_POLLIN)
        {
            char* buff = NULL;
            int len = nn_recv(sb, &buff, NN_MSG, NN_DONTWAIT);
            if (len < 0) {
                continue;
            }
            std::cout << "Work!" << std::endl;
            std::string req(buff, len);
            std::cout << req << std::endl;
            nn_freemsg(buff);
        }
    }
    nn_close(sb);
}

int main()
{
    WorkerType* fp = new WorkerType(&pub);
    WorkerType* fb = new WorkerType(&sub);
    std::cout << "-------------" << std::endl;
    SleepFor(15);
    std::cout << "--------------" << std::endl;
    fp->join();
    fb->join();
}
```
If `WorkerType` is std::thread, all things work well. But if I switch to 'boost::fiber', it would not work. So it seems that nanomsg could not use in fiber?

**Comment by webbery** [comment]
It seems not easily to use for developer. Here is the [link](https://www.boost.org/doc/libs/1_69_0/libs/fiber/doc/html/fiber/integration/deeper_dive_into___boost_asio__.html) about `boost.fiber` in `boost.asio`.

**Comment by gdamore** [comment]
I don't think you can replace threads with fibers in libnanomsg.  If someone else wants to undertake this, I'd welcome the effort, but I will not be spending any time on it -- this is clearly outside the support matrix for libnanomsg.

You *might* have better luck with NNG, but I wouldn't count on it.  (Probably with NNG you'd wind up having to change the underlying platform code, which is meant to be possible, but in this case the effort might be significant since you'd also need to change the poller code to use a strategy that is compatible with fibers.)

For now, I'm closing this for libnanomsg.
