### ISSUE TITLE
pubsub can messages be lost in inproc

### ISSUE THREAD

**Issue by d01010101** [nanomsg/nanomsg#1023]
When using inproc, i.e. no sockets are really involved in transport, can there be message drop?
In particular, as there are no callbacks, a sub node has a short break between two calls to nn_recv, when it does not wait. If, during that break, a common publisher socket publishes two different topics, can some message be lost?

**Comment by d01010101** [comment]
By the way, there in nothing about this in https://nanomsg.org/v0.5/nn_pubsub.7.html and not even in https://nanomsg.org/gettingstarted/nng/pubsub.html

If there is a loss possible, then it would be an in-process communication scheme which does only best-effort without warning.

**Comment by gdamore** [comment]
It absolutely is possible for pub/sub to be dropped with inproc.  All it takes is for you to consume messages from the subscriber less often (or less timely) than you publish them.  This can happen with one thread, or many threads.  If you use an event loop driven scheme, it should be very unlikely (maybe even impossible) to occur, since you would then be consuming as often as you produce, but event loops are not the only valid single process architecture.

**Comment by gdamore** [comment]
No bug, this is just a question, so closing it.
