### ISSUE TITLE
nn_send does not block when server is down

### ISSUE THREAD

**Issue by cr-galrosen** [nanomsg/nanomsg#1037]
I run a simple client/sever with REQREP scalability protocol, the transport is IPC.
Steps:
1. Run the server
2. Run the client with a sleep before the call to nn_send
3. Kill the server

The nn_send complete successfully. The flags is zero.
As I understand it should be blocked on the nn_send, am I missing something here.

It happened on both Windows and Mac.
This version is 1.1.5

**Comment by cr-galrosen** [comment]
It may as designed because when testing it with the NN_PAIR socket it does block.
If this is true then how client with REQREP protocol knows about failure of the other end (the server).

**Comment by gdamore** [comment]
The REQ code keeps track of the pipe it sent a request to.  If the pipe disconnects, it will immediately resend the REQ somewhere else (if somewhere else is available). If nothing is available, it will resend when such a connection is established.

Basically once you send with REQ, we keep the request and track it.

PAIR is quite different.  It does flow control, and but is otherwise stateless.
