### ISSUE TITLE
surveyor NN_RCVFD

### ISSUE THREAD

**Issue by chrutta** [nanomsg/nanomsg#1038]
Hi,

nanomsg version 1.0.0

I create a surveyor socket and get NN_RCVFD from the socket to use with select() to also handle other Linux signals (instead of using nn_poll), but it seems like my call to FD_ISSET is always returning true for the surveyor RCVFD, even when there is no data to receive (no survey in progress) and errno tells me rightly that the socket is in the incorrect state when trying to receive.

Could there be a bug with the surveyor pattern? Using NN_RCVFD with select() works fine with SUB and REP.

Thanks!
Christer

**Comment by gdamore** [comment]
Sounds like a bug.  Can you try 1.1.4 -- the latest version?  There are a lot of fixes, and while nothing stands out immediately for me here, its possible I missed something.

I should also say at this point that I'm pretty focused on NNG instead of nanomsg, which is in sustaining only mode.  NNG is compatible with nanomsg.

**Comment by chrutta** [comment]
Thanks for quick feedback. I'm working within a complicated build system, so it'll take some time until I can try a later version.

For now I'm just solving this by ignoring survey receive errors if there is no survey in progress and placing a short sleep to avoid choking the main loop.

If I get the chance to try the latest nanomsgversion I will let you know.

**Comment by gdamore** [comment]
I'm closing this -- the submitter has a workaround and has not replied with a test for a newer version.
