### ISSUE TITLE
Unable to communicate to server when server is run as root

### ISSUE THREAD

**Issue by jetacpp** [nanomsg/nanomsg#1043]
Hello,
I created server and client executables implementing REQ and REP pattern. Everything worked fine when I run both with user privilege. However, when I run server as root, client could not connect or communicate to server.
I need to start server as root for permission reason. Is there any specific reason to why it was not working and what could be the workaround for the issue ?

**Comment by gdamore** [comment]
Need more data here.

What transport were you using?  IPC?  If IPC then you have to make sure that the permissions are correct on the socket, because by default it probably won't let anyone connect.  (Also, check that umask() is set properly, since that might leave some surprises.)

tcp:// over loopback (127.0.0.1) is *usually* more reliable than UNIX domain sockets for various reasons.  Permissions like this is just one of them.

**Comment by jetacpp** [comment]
I tested with basic REQ REP example which used "ipc:///tmp/reqrep.ipc" transport. System is Ubuntu 18.04. I did noted that when server was run as root it created root owned file /tmp/reqrep.ipc.
I tried chmod 777 this file to see if server may just open it but it seemed server created new overwrite anyway.
I wasn't able to find documentation on the the following points you mentioned, please clarify:
- setting permission on the socket.
- by default it won't let anyone connect.

What permission on "/tmp/reqrep.ipc" is required in order for client to connect and communicate to rooted server ?

Switching over to tcp://127.0.0.1 did allow root server and user client to communicate.

**Comment by jetacpp** [comment]
I was able to use umask to set "/tmp/reqrep.ipc" to 777 and client was able to communicate with server. Thanks for your help !
