### ISSUE TITLE
NN_REP socket and NN_RCVFD do not work on windows as expected

### ISSUE THREAD

**Issue by imuzychuk** [nanomsg/nanomsg#1050]
Hi, 
I am using event loop (glib) on windows and want to receive request on NN socket with REP patter on windows. I should receive requests from multiple workers, few workers may send request at the same moment of time.

What I am doing:
1. Create NN socket NN_REP
2. Get NN_RCVFD with nn_getsockopt
3. Listen on IN events on NN_RCVFD with glib
4. When NN_RCVFD socket is triggered, I considered that some worker start sending data to me. 
5. Stop listening on NN_RCVFD.
6. Call nn_recv with NN_DONTWAIT. If EAGAIN returned - call nn_recv in 50 milliseconds again (can do it multiple times). Otherwise I consider that received request.
7. Process request
8. When I got response to send back I start sending it with nn_send with NN_DONTWAIT
9. If EAGAIN returned - call nn_send in 50 milliseconds, may do it multiple times until message is send
10. After response sent  - start listening on NN_RCVFD again

This approach works well for me on Linux. But Windows at some point stops trigger NN_RCVFD when data is sent from worker. So worker send request fails with timeout. 

Socket protoc - NN_RCVFD, with IPC path

I can provide a working example which reproduces the issue is needed

**Comment by gdamore** [comment]
Sorry, I don't know why I didn't get updates from GitHub -- probably because I marked this as sustaining.

Your 50 msec wait feels like a hack.  I'm not sure what glib does with "listening" to events.  You should watch for a readable select() event.  If you read the message, it should clear.  If you get EAGAIN, you should go back to waiting for the event.

The listen/stop listening thing seems brittle to me.

**Comment by gdamore** [comment]
I'm closing this as it's stale with no feedback.
