### ISSUE TITLE
High cpuload in Nanomsg thread

### ISSUE THREAD

**Issue by clearday4** [nanomsg/nanomsg#1107]
Hello, I am currently running a real middleware service using the nanomsg pipe model.
Currently, the packets processed by nanomsg are TX 423 Mbps and RX 417 Mbps, which is quite a lot of messages being processed.
However, only the nanomsg thread goes up to 90% ~ 100%.  not user thread.

My question is as follows.
I'm only using one nanomsg worker thread, will increasing this solve my performance problem?
In the problematic situation, I caught statistics from strace, 
and it seems that epoll_ctl has the most occupancy and there's noticeable futex error.

strace -c -p 288
strace: Process 288 attached
^Cstrace: Process 288 detached
% time seconds usecs/call calls errors syscall
------ ----------- ----------- --------- --------- ----------------
33.07 53.948596 40 1343685 epoll_ctl
26.54 43.295889 61 701505 recvmsg
20.45 33.360230 44 757061 48988 futex
14.94 24.378292 53 452400 write
2.97 4.852970 76 63216 epoll_wait
2.03 3.319307 52 62917 read
------ ----------- ----------- --------- --------- ----------------
100.00 163.155284 48 3380784 48988 total

Will increasing the number of nanomsg worker threads lower the cpu load in this situation?

**Comment by gdamore** [comment]
If you are using legacy libnanomsg then that is all you can do. There is no support for more concurrency in libnanomsg. You can try NNG.

**Comment by clearday4** [comment]
I'm currently using push and pull sockets.
would I simply initializing workers equal to the number of cores in nn_pool_init() function if I want to increase the number of worker threads to match the number of cores where they're bound?

**Comment by gdamore** [comment]
If you look, you'll see this comment:
```
/*  TODO: The dummy implementation of a thread pool. As for now there's only
    one worker thread created. */
 ```
Basically, libnanomsg doesn't have real multithreading support.  I don't think it would be trivial to fix this, because you have to start to worry about concurrency for the pollers, and that's not necessarily trivial because of bugs in some of them (especially Linux has gotchas here.)

If you want higher concurrency than you're getting, you should probably look at NNG.  Although NNG is not as concurrent as it could be - and I think actually on Linux the epoll implementation there is also single threaded -- but the underlying design is at least designed for concurrency (and indeed on some systems it actually *is* concurrent -- for example on Windows.

There are, as I said, gotchas about handling the poller's concurrently correctly -- so it isn't necessarily trivial.

You could reach out to `info@staysail.tech` to funding enhancements to the NNG pollers if you have a commercial need for this.  It's certainly quite doable.  Probably we (Staysail Systems) won't be very interested in trying to make such enhancements to legacy libnanomsg though.

If you're not even getting more than 1Gbps it seems surprising... it should be easy to get significantly higher than that, but if your CPU cores are very low performance that might be an issue.

**Comment by gdamore** [comment]
I'm going to close this for now.  We're not going to add concurrency to this project - -but we could do so to specific NNG ports (we plan to in fact!)
