### ISSUE TITLE
Add SOL_ENDPOINT option level

### ISSUE THREAD

**Issue by tailhook** [nanomsg/nanomsg#168]
It denotes options that will be applied for the next nn_connect()/nn_bind() instead of socket-wide, as discussed in #165

**Comment by gdamore** [comment]
We have transport level options, and the architecture of nanomsg makes it hard to see endpoints from the client application.  With transport layer options, is this still needed?

Certainly the idea of setting an option that only applies to the next nn_connect() seems kind of crummy and very un-threadsafe.  What would be better would be to pass explicit options to nn_connect, nn_bind.  That means having new functions that take some kind of option value.

Frankly, I'm not too thrilled with that either.

I'd really want to see a compelling use case for this feature, otherwise I'm inclined to just close it.

**Comment by gdamore** [comment]
We will be doing this a different way under libnng, where you can actually issue options directly to the endpoint, instead of going through the socket.  This turns out to be really important since the socket can have multiple endpoints.

For nanomsg, I'm not going to solve this at all.  But stay tuned for libnng.  Closing this one against libnanomsg as "will not fix".
