### ISSUE TITLE
Assertion error on Req/Rep pattern

### ISSUE THREAD

**Issue by daborg69** [nanomsg/nanomsg#172]
Scenario:  
-- Running a Req/Rep pattern.
-- 2 Servers running that can reply to clients.
-- Everything is fine, with clients sending requests to different servers.
-- Simulate a network failure or server failure by killing one of the servers.

Result:
 -- Clients crash with following assertion: 
Assertion failed: self->state == NN_USOCK_STATE_ACTIVE (c:\b_programming\github\nanomsg\src\aio\usock_win.inc:326)

**Comment by marchon** [comment]
Was this issue really closed as part of #175? If so can we close this issue?

**Comment by djc** [comment]
#175 doesn't seem related to me.

**Comment by snikulov** [comment]
I think you can close this issue.

**Comment by djc** [comment]
@snikulov can you please explain why you think so? Thanks!

**Comment by snikulov** [comment]
@djc Well, because:
 * I was also observed described issue on my Windows box while ago.
 * Changes suggested by @tailhook and @norsd targeted to solve assertion was combined and merged into upstream, and it solves the issue at least for me.
 * Original submitter @daborg69 not responded for long period (perhaps it move away from nanomsg or because issue not present on latest release).

So I see no reason to keep it open.

**Comment by djc** [comment]
Alright, thank you!
