### ISSUE TITLE
SUB socket doesn't automatically re-connect after server restarts

### ISSUE THREAD

**Issue by brunoqc** [nanomsg/nanomsg#182]
I'm using pubsub with tcp and if I stop and restart the server, the client stops receiving messages.

I'm using the latest commit 99131593aed8eab2795ba4bfaaea32b0a64b14c8 on Windows 7 (64-bit).

I built nanomsg using MSVC 2012 express.

Here's Go code to reproduce.

server
```go
package main

import (
	"fmt"
	"time"

	"github.com/op/go-nanomsg"
)

func main() {
	pub, errNew := nanomsg.NewPubSocket()
	if errNew != nil {
		panic(errNew)
	}
	defer pub.Close()

	if _, err := pub.Bind("tcp://0.0.0.0:8861"); err != nil {
		panic(err)
	}

	c := time.Tick(1 * time.Second)
	for now := range c {
		msg := now.String()
		fmt.Println("->", msg)
		pub.Send([]byte("chan "+msg), 0)
	}
}
```

client
```go
package main

import (
	"fmt"

	"github.com/op/go-nanomsg"
)

func main() {
	sub, errNew := nanomsg.NewSubSocket()
	if errNew != nil {
		panic(errNew)
	}
	defer sub.Close()

	if err := sub.Subscribe("chan"); err != nil {
		panic(err)
	}

	if _, err := sub.Connect("tcp://127.0.0.1:8861"); err != nil {
		panic(err)
	}

	for {
		buf, err := sub.Recv(0)
		if err != nil {
			panic(err)
		}

		fmt.Printf("<- %s\n", buf)
	}
}
```

**Comment by gdamore** [comment]
So, I feel that this change goes against the intended design of nanomsg, which is that apps need never notice the arrival and departure of connections.

Ultimately this problem is caused by another issue -- which is that on many platforms you won't notice a lost connection unless you have an outstanding read().  We need to make sure we always have outstanding blocking reads going on; which is tricky given the non-threaded design of the library.

I'm going to have to think about this some more, but this PR's approach is wrong (the API impact to the client), so I'm closing the PR.   The bug will remain open.

**Comment by gdamore** [comment]
Doe we know, is this still a problem with the current head bits?  I have a sneaking suspicion that I've fixed the root problem here.

**Comment by brunoqc** [comment]
I ran the two nanocat commands at the same time. If I restart the server one, the client begin again to get the 'hello' messages.

I'll try the Go code if the Go binding module is not too out-of-date.

**Comment by brunoqc** [comment]
The Go code works as well.

Note that I tested both the Go code and nanocat on Windows 10. I don't have access to a Window 7 machine anymore.

**Comment by elektito** [comment]
Was this problem fixed? I have the same problem here on Linux. With TCP the subscriber reconnects, with IPC it doesn't. Checked with nanocat, too. I tried both the 0.8-beta release and the latest code on the master (8f873b45).
