### ISSUE TITLE
Tests failing with VS2010 Win32

### ISSUE THREAD

**Issue by wirebirdlabs** [nanomsg/nanomsg#269]
The test failures are intermittent when rebuilding RUN_TESTS with VS2010 Win32. Roughly 2/3 of the time all tests pass, and roughly 1/3 of the time there are anecdotally two types of failure modes:

1) `tcp_shutdown` will be the only test to fail out of the 29 tests with the following output:

`Assertion failed: src == NN_SOCK_SRC_EP && type == NN_EP_STOPPED` 

2) `tcp_shutdown` or `ipc_shutdown` will fail, making most subsequent tests fail also.

```
tcp_shutdown
No buffer space available [119] (..\..\src\transports\tcp\ctcp.c:619)
```

which leads to the following tests all throwing the same error:

```
7:pair
8:pubsub
9:reqrep
10:pipeline
11:survey
12:bus
13:block
14:term
15:timeo
16:iovec
17:msg
18:prio
19:poll
20:device
21:emfile
22:domain
27:separation
28:zerocopy
29:shutdown

No buffer space available [119] (c:\users\jack\repo\ftw-nanomsg\src\utils\efd_win.inc:191)
```

**Comment by gdamore** [comment]
Fixed in ab699df74978645ebe5bb53f0b602ba4bf32ed4b

That said, tcp_shutdown is particularly vile to the platform, and I found that it was unsafe to run before other tests, as it would leave the system in a state that broke other tests.  I'm not sure why, or whether this is generic to Windows or specific to our CI provider (AppVeyor).
