### ISSUE TITLE
Performance of TCP vs inprocess

### ISSUE THREAD

**Issue by maattdd** [nanomsg/nanomsg#319]
I'm using the following scenario:
* 2 senders each one in a dedicated thread
* 1 receiver in main thread.
* small messages (48 bytes)

The average time to receive a message for inprocess is 2900ns, but only 1100ns in TCP.
Is this the expected behavior? I was under the impression that inprocess should be faster.

This is somehow related to issue #300

**Comment by marchon** [comment]
We should profile this...

**Comment by gdamore** [comment]
Actually, this may be related to other issues.  There is a crazy amount of logic in the code to offer the same file descriptor semantics.  Ultimately, I suspect the problem has to do with the various extra syscalls that inproc has to do (surprise!) to get signaling on polled file descriptors, and may also relate to a race condition in inproc.

That said, I'm far far more concerned about correct behavior than by inproc taking 2.9us to deliver a message.

**Comment by gdamore** [comment]
I'm going to punt on this.  inproc needs a full rewrite (see #429 ) anyway, and perhaps we can address it at that time.  Having said that, the problem is that even inproc requires syscalls to coordinate so that nn_select() works.

**Comment by gdamore** [comment]
See #324  - this is going to hurt even worse.

But the thing is that nanomsg will *always* be quite a lot slower than zmq -  because it uses a whole round of extra system calls for the poll notification.  ZMQ doesn't need those because it doesn't try to present an API that select() or poll() can use.

The only way to fix *that* is to abandon the select/poll API compatible, and that looks like a major rewrite.
