### ISSUE TITLE
inproc doesn't transport message headers

### ISSUE THREAD

**Issue by sustrik** [nanomsg/nanomsg#324]
Make a REQ/REP socket pair connected via inproc. Send a message to the REQ socket. The body of the message arrives at REP. Not so message headers.

**Comment by marchon** [comment]
Does the merged change solve this problem?

**Comment by gdamore** [comment]
Not sure about libnanomsg, but in mangos I provide TP specific content to the consuming application.  This is useful because that info can include things like getpeerucred(Solaris), or TLS certificate information.  This can allow transport layer authentication be usefully consumed for transports that offer it.

**Comment by gdamore** [comment]
Part of our test suite could validate this.  In fact, adding an inproc member to a device handler would "prove" this.

**Comment by gdamore** [comment]
This is critical for making devices that work properly with req/rep or surveyor/respondent.  Frankly, inproc is not really usable without this.

**Comment by gdamore** [comment]
Actually, given this, I can test with the device framework we already have.  Stay tuned.

**Comment by gdamore** [comment]
Well, I can reasonably confirm that inproc still doesn't transport message headers.

**Comment by gdamore** [comment]
Well, that makes *no* sense.  It should by reading the code actually transport them.  But it doesn't seem to work.  Stay tuned.

**Comment by gdamore** [comment]
Actually, it makes *perfect* sense.  inproc has already preparsed the SP headers.

**Comment by gdamore** [comment]
So - the problem seems to be the whole mess of preparsed headers basically being *wrong*.

I don't want to expend energy to fix this right now.  Frankly, optimizing inproc to avoid data copies is stupid.  People shouldn't be moving huge amounts of data via inproc, and making it go fast seems kind of pointless.

However, making it *correct* is very important.

So for now what I'm going to do is make it just do a data copy just like TCP et. al.  It works.

And now I'm wondering how many other bugs in inproc this will fix (a few I guess) -- certainly nn_device() and inproc, as well as using inproc with raw mode, should be much much better now.
