### ISSUE TITLE
Feature Reqest: Windows XP Compability

### ISSUE THREAD

**Issue by zerotacg** [nanomsg/nanomsg#334]
As mentioned in #330 and just to keep it separated, current implementation is depending on Windows version 6.00 (Vista) and it seems as if it is only CancelIoEx that prevents compatibility. So this might be within reach.
It will need some research though, the comment in the source mentions some issues and a quick search brings up something as well [2]. They link to how boost handles it, so that might give some leads, but maybe it's not satisfactory for nanomsg's needs.

[1] https://github.com/nanomsg/nanomsg/issues/330#issuecomment-62470467
[2] https://stackoverflow.com/questions/3921111/how-to-find-out-when-cancelio-is-done

**Comment by gdamore** [comment]
I'm closing this.  I can't verify this works, and CancelIO is known to be insufficient to the task.  We might look at changes which might support making WinXP work better in the future, but this is so far a complete anti-goal.

Worse, XP support needs to be determined at run time, because I really, really don't want to try to support a binary built for XP on newer Windows platforms.

Meanwhile the XP platform is aging.  Formally, there have been no more security or technical patches for the past two years (Microsoft ceased all support activity in April 2014.)   Even Vista is in extended support at this point.
