### ISSUE TITLE
leak in xrep code

### ISSUE THREAD

**Issue by gdamore** [nanomsg/nanomsg#385]
I was reading the xrep code, and I notice that when a message is going to be discarded due to pushback or lack of a sender, we return 0.  But we don't do nn_msg_term(), which I believe is necessary to release the resources of the message.

The code is here, in nn_xrep_send():

```
    /*  Find the appropriate pipe to send the message to. If there's none,
        or if it's not ready for sending, silently drop the message. */
    data = nn_cont (nn_hash_get (&xrep->outpipes, key), struct nn_xrep_data,
        outitem);
    if (!data || !(data->flags & NN_XREP_OUT))
        return 0;
```

Just above that is a case where we do clean up, and the two cases are indistinguishable from the caller, so I think one or the other is incorrect:

```
    /*  We treat invalid peer ID as if the peer was non-existent. */
    if (nn_slow (nn_chunkref_size (&msg->sphdr) < sizeof (uint32_t))) {
        nn_msg_term (msg);
        return 0;
    }
```

**Comment by bnewbold** [comment]
I just came across this same section of code. Just staring at it, I think there should be a `nn_msg_term(msg)` when there is no such pipe.

I got here because, despite the comments in source, it seems crazy to me not to return some sort of error code in either condition, but particularly lacking an EINVAL for invalid peer ID (aka, when the headers are just plain wrong/empty).

**Comment by gdamore** [comment]
I think the idea is that we could passing in data from a layer that doesn't realize the peer has gone -- e.g. if the peer has disconnected.  We could change the API to return an error, and I think this might be a good idea, but its out of scope for this bug.
