### ISSUE TITLE
HTTP/2

### ISSUE THREAD

**Issue by reqshark** [nanomsg/nanomsg#395]
@wirebirdlabs, when you and Martin started working on the nanomsg websocket, around the time when those commits began, do you remember when you explained to me reasons for selecting websocket?

I mentioned looking into Server Sent Events and your reply: 

> it doesn't seem SSE fits the required semantics for all the nanomsg scalability protocols, where as ws:// does.

@gdamore, this is something, btw I think a new important turn in the history of the protocol, that deserves your attention as well... while I've only started catching up on the new standards track for HTTP/2,  it looks like there is tremendous alignment underway with the natural socket interface designs and semantics for scalability protocols we have in nanomsg, namely:
* [stream identifiers and stream concurrency](https://tools.ietf.org/html/draft-ietf-httpbis-http2-17#section-5.1.1)
* [server push and push requests](https://tools.ietf.org/html/draft-ietf-httpbis-http2-17#section-8.2)
* [request multiplexing](https://tools.ietf.org/html/draft-ietf-httpbis-http2-17#section-5)

Also the [chrome team may have some client-ready](http://blog.chromium.org/2015/02/hello-http2-goodbye-spdy-http-is_9.html) releases in the next few weeks. 

IMO, nanomsg SP protocols may fit HTTP/2 standards  *even more so* than websocket and I'll make an easy call right now: I predict [HTTP/2](https://http2.github.io/) is going to rival websocket and eventually in the long term, replace it.

**Comment by gdamore** [comment]
> On Mar 28, 2015, at 2:18 PM, Bent Cardan <notifications@github.com> wrote:
> 
> @wirebirdlabs <https://github.com/wirebirdlabs>, when you and Martin started working on the nanomsg websocket, around the time when those commits began, do you remember when you explained to me reasons for selecting websocket?
> 
> I mentioned looking into Server Sent Events and your reply:
> 
> it doesn't seem SSE fits the required semantics for all the nanomsg scalability protocols, where as ws:// does.
> 
> 
That’s still the case.  SSE is one-way — server send to browser.  websocket is full duplex.
> @gdamore <https://github.com/gdamore>, this is something, btw I think a new important turn in the history of the protocol, that deserves your attention as well... while I've only started catching up on the new standards track for HTTP/2, it looks like there is tremendous alignment underway with the natural socket interface designs and semantics for scalability protocols we have in nanomsg, namely:
> 
> stream identifiers and stream concurrency <https://tools.ietf.org/html/draft-ietf-httpbis-http2-17#section-5.1.1>
> server push and push requests <https://tools.ietf.org/html/draft-ietf-httpbis-http2-17#section-8.2>
> request multiplexing <https://tools.ietf.org/html/draft-ietf-httpbis-http2-17#section-5>
Most of the enhancements in HTTP/2 are targeted at improving experiences with browsing.  That is, the server push for example is sort of a “server-side look-ahead cache” — its not really the same thing as push vs. pull, but an optimization done to reduce round trips.  The multiplexing over a single TCP channel is nice, and I do think that with websocket over HTTP/2 it will reap some rewards for us.  That said, the implementation of websocket in libnanomsg is kind of toylike in its simplicity — adding support for full HTTP/2 semantics is likely to be rather a large task.  I wouldn’t look to see that work happen anytime soon.

Far more likely is a full rewrite of libnanomsg with an internal design that is easier for extension (but may make other sacrifices, which make it harder to embed in certain implementations such as OS kernels, for example).  That said, I wouldn’t rate the likelihood of even *that* at very high, since as far as I know I’m the only one likely to undertake such an endeavor, and I don’t exactly have a surplus of time on my hands.
> Also the chrome team may have some client-ready <http://blog.chromium.org/2015/02/hello-http2-goodbye-spdy-http-is_9.html> releases in the next few weeks.
> 
> IMO, nanomsg SP protocols may fit HTTP/2 standards even more so than websocket and I'll make an easy call right now: I predict HTTP/2 <https://http2.github.io/> is going to rival websocket and eventually in the long term, replace it.
> 

I think that its rather premature to make such a prediction.  websocket’s exists to offer a binary protocol to application developers, for use in the browser.  Its unclear to me that the same semantics are directly available with HTTP/2 that websockets gives.  They may be.   There are also discussions afoot about layering websockets on top of HTTP/2, but I can’t see that any consensus has been reached on that yet.

The following blog post is salient: https://webtide.com/http2-last-call/ <https://webtide.com/http2-last-call/>

I’m hopeful for the future of HTTP/2, but I’m also not ready to spend a bunch of time heading off without having some idea where the destination lies.

	- Garrett

**Comment by reqshark** [comment]
> the implementation of websocket in libnanomsg is kind of toylike in its simplicity.

Sounds good to me! 

> Far more likely is a full rewrite of libnanomsg with an internal design that is easier for extension (but may make other sacrifices, which make it harder to embed in certain implementations such as OS kernels, for example).

Small is beautiful. Compatibility is better than purity. Simplicity is better than anything.

> That said, I wouldn’t rate the likelihood of even *that* at very high, since as far as I know I’m the only one likely to undertake such an endeavor, and I don’t exactly have a surplus of time on my hands.

Fair enough.

> I think that its rather premature to make such a prediction.  websocket’s exists to offer a binary protocol to application developers, for use in the browser.  Its unclear to me that the same semantics are directly available with HTTP/2 that websockets gives.  They may be. There are also discussions afoot about layering websockets on top of HTTP/2, but I can’t see that any consensus has been reached on that yet.

HTTP operates under semantic obligation to close the *response* after the last fragment. I'm hesitant to say close the TCP connection since proxy servers started implementing keep-alive and that's widely used.

Contrast that pattern with websocket: 

> websockets exist to offer a binary protocol to application developers, for use in the browser.

True, it's a two-way messaging pattern that seems consistent with scalability principles/protocols/patterns we see in nanomsg.

But that's just [section 8 of the HTTP/2 draft](https://tools.ietf.org/html/draft-ietf-httpbis-http2-17#section-8)! :rocket: :rocket: 

Further into section 8, push requests are defined as essentially the semantic inverse of the `GET`/`POST` style.  `HTTP/2` ushers in a new two-way messaging protocol native to the TCP connection. 

Of course the header format and framing designs are not the most attractive aspect of the protocol, but in HTTP/2 I see it as a minimal, albiet ugly, semantic requirement to bi-directional TCP sockets.

**Comment by reqshark** [comment]
> I’m hopeful for the future of HTTP/2, but I’m also not ready to spend a bunch of time heading off without having some idea where the destination lies. - Garrett

I can understand that, save time, you might be interested to check these out first: 
* https://github.com/bradfitz/http2
* https://github.com/Jxck/http2

and one my favorites of the implementations I've seen so far: https://github.com/h2o/h2o

**Comment by gdamore** [comment]
> On Mar 28, 2015, at 3:47 PM, Bent Cardan <notifications@github.com> wrote:
> 
> the implementation of websocket in libnanomsg is kind of toylike in its simplicity.
> 
> Sounds good to me!
> 

Um, in this case that wasn’t really meant as a compliment.  Its just sufficient to meet HTTP/1.1 and switch to websocket.  It can’t really support any other interesting parts of the HTTP spec, and it is impossible to layer it with TLS, or to make a really useful websocket server (for example, it totally ignores the resource specified, which makes it impossible to multiplex multiple sockets or applications on the same port).  Put another way, the implementation is toylike enough to meet the requirements of websocket from an RFC standpoint, but totally miss the *point*.  That said, it would be non-trivial to do much more within libnanomsg, because of libnanomsg’s design constraints.  (I’ve done a lot more here with the freer constraints available to me in mangos — plus having a rich http and websocket framework to utilize.)

> I think that its rather premature to make such a prediction. websocket’s exists to offer a binary protocol to application developers, for use in the browser. Its unclear to me that the same semantics are directly available with HTTP/2 that websockets gives. They may be. There are also discussions afoot about layering websockets on top of HTTP/2, but I can’t see that any consensus has been reached on that yet.
> 
> HTTP operates under semantic obligation to close the response after the last fragment. I'm hesitant to say close the TCP connection since proxy servers started implementing keep-alive and that's widely used.
> 
> 
Not just proxy servers.  HTTP/1.1 keeps the TCP channels open by default.  This was one of the main advantages to 1.1 over 1.0.  (The other big advantage is that in 1.1 the Host: is specified in the protocol, allowing for aliasing based on CNAMEs, avoiding the requirement to set up IP addresses and A records for every possible alias you might want to serve from a single server machine.)

> Contrast that pattern with websocket:
> 
> websockets exist to offer a binary protocol to application developers, for use in the browser.
> 
> True, it's a two-way messaging pattern that seems consistent with scalability principles/protocols/patterns we see in nanomsg.
> 
> But that's just section 8 of the HTTP/2 draft <https://tools.ietf.org/html/draft-ietf-httpbis-http2-17#section-8>!  
> 
Section 8 starts with language that makes it clear that the intention is to retain the semantic REQUEST/RESPONSE model of HTTP/1.1.  To wit:

   HTTP/2 is intended to be as compatible as possible with current uses
   of HTTP.  This means that, from the application perspective, the
   features of the protocol are largely unchanged.  To achieve this, all
   request and response semantics are preserved, although the syntax of
   conveying those semantics has changed.

So, it would be a mistake, IMO, to assume that it semantically is anything at all like a free-form binary protocol with completely asynchronous messaging.  (In HTTP request/responses are synchronous, in the sense that you don’t get a server response until after you’ve asked for a request.)

If you read the details of Server push, you’ll see that it is still intended for caching purposes, and indeed the client is given some control over whether server pushes should be used or not.  (SETTINGS_PUSH_ENABLE).

Now it may be that people will figure ways to abuse the protocol to get server-push style behaviors for supporting semantics associated with push.  But notably, the logic is really not in HTTP/2 itself to support true arbitrary bi-directional messages.  For example, having a pattern where the server sends a message to the client, and *gets a reply back*, is kind of not there.  And every message sent by the client needs to be responded by the server.   Yes, you can hack around these, and make something that works— but you’re trying to use a hammer to drive a screw.  Can be done, but the fit is wrong, and the results are ugly.
> Further into section 8, push requests are defined as essentially the semantic inverse of the GET/POST style. HTTP/2 ushers in a new two-way messaging protocol native to the TCP connection.
> 

NO it does’t.  See above.

> Of course the header format and framing designs are not the most attractive aspect of the protocol, but in HTTP/2 I see it as a minimal, albiet ugly, semantic requirement to bi-directional TCP sockets.
> 
> 

If you want bidirectional TCP sockets… um… there is TCP.  If you want bidirectional communication within a browser/web semantic, we have websocket.  We don’t need HTTP/2.  There is really zero value that HTTP/2 can offer over websocket here.  (Well, you can argue that having fewer underlying TCP connections without head-of-line blocking can be a win for some servers running at extreme scales and needing multiple connections per client.  Its unclear to me that this is a significant enough benefit to be worth the various sacrifices you have to make along the way.)

	- Garrett

**Comment by reqshark** [comment]
> Further into section 8, push requests are defined as essentially the semantic inverse of the GET/POST style. 

I must have been interpreting [Section 8.2.1,  Push Requests](https://tools.ietf.org/html/draft-ietf-httpbis-http2-17#section-8.2.1):

   *Server push is semantically equivalent to a server responding to a
   request; however, in this case that request is also sent by the
   server, as a PUSH_PROMISE frame.*

> HTTP/2 ushers in a new two-way messaging protocol native to the TCP connection.

>> NO it does’t.  See above.

OK that's absolutely right. That is <strong>not where HTTP/2</strong> ushers in the async bi-directional specifications. Server push requests are not the right comparison to that type of two-way communication, like websocket. 

#### *But the `HTTP/2` Streams might be*:

Stream DATA frames (type=0x0) convey arbitrary, variable-length sequences of octets associated with a stream. One or more DATA frames are used, for instance, to carry HTTP request or response payloads. [see, e.g. 6.1](https://tools.ietf.org/html/draft-ietf-httpbis-http2-17#section-6.1)

So after re-reading the sections on push requests/responses, I completely agree with you here:

> If you read the details of Server push, you’ll see that it is still intended for caching purposes, and indeed the client is given some control over whether server pushes should be used or not.  (SETTINGS_PUSH_ENABLE).

And I would agree with you further on this point, but for the Stream Data Spec:

> So, it would be a mistake, IMO, to assume that it semantically is anything at all like a free-form binary protocol with completely asynchronous messaging.  (In HTTP request/responses are synchronous, in the sense that you don’t get a server response until after you’ve asked for a request.)

The initial impression I had and description of Push Request you're responding to was certainly a mistake of understanding on my part. Moreover, at this point I think the idea of `PUSH_PROMISEs` are akward distortions of the HTTP request/response practices and definitions, at best.

> If you want bidirectional communication within a browser/web semantic, we have websocket.  We don’t need `HTTP/2`.

From this perspective, Websocket looks simpler and more straightforward, so I guess time will tell whether the `HTTP/2` streams end up replacing them. 

OK.. now that we've cleared that up, I'd like to return to the first point you made, because there was something very interesting there having less to do with `HTTP/2` standards track and more to do libnanomsg and it's ability to support additional extensions or modularity:

> the implementation is toylike enough to meet the requirements of websocket from an RFC standpoint, but totally miss the *point*.  That said, it would be non-trivial to do much more within libnanomsg, because of libnanomsg’s design constraints. 

@gdamore, where do you see design constraints? Where are they the worst? And more importantly how can we improve these areas of the library? Is there a specific layer or convention, encumbering further extension/modular development?

**Comment by gdamore** [comment]
> If you want bidirectional communication within a browser/web semantic, we have websocket. We don’t need HTTP/2.
> 
> From this perspective, Websocket looks simpler and more straightforward, so I guess time will tell whether the HTTP/2 streams end up replacing them.
> 
> OK.. now that we've cleared that up, I'd like to return to the first point you made, because there was something very interesting there having less to do with HTTP/2 standards track and more to do libnanomsg and it's ability to support additional extensions or modularity:
> 
> the implementation is toylike enough to meet the requirements of websocket from an RFC standpoint, but totally miss the point. That said, it would be non-trivial to do much more within libnanomsg, because of libnanomsg’s design constraints.
> 
> @gdamore <https://github.com/gdamore>, where do you see design constraints? Where are they the worst? And more importantly how can we improve these areas of the library? Is there a specific layer or convention, encumbering further extension/modular development?
> 
> 

The design constraints involve hard tie to file descriptors and POSIX like API, and a requirement to be portable even into runtimes where you can’t for example use native threading.  This last case forces a design to use asynchronous I/O in some rather painful state-machine constructs.  The internal construction as a result is inordinately complex, and pretty much impossible to extend to systems like OpenSSL.  (Well, not *impossible*, but of such a high complexity that I think it may actually be less effort to redesign from scratch.)

Btw, these same design constraints make it really hard, for example, to attach to a broader “HTTP” transport or framework.

	- Garrett

**Comment by wirebirdlabs** [comment]
@reqshark, I'm still confused how HTTP/2 really maps to the spirit of nanomsg, but it remains clear and desirable to use WebSocket as a transport option for nanomsg. HTTP/2 is exciting and useful for other reasons, but doesn't feel so relevant to nanomsg.

I agree with @gdamore's sentiments toward the ws:// implementation in nanomsg core, as I'm familiar with the implementation. During the time of its initial development, we had some brief discussions as to what/why nanomsg+websocket, just enough eek out a shippable prototype. I expected that contribution to spur additional development and thoughts from other contributors, but it came during a transition period in the nanomsg project and hasn't really continued to further develop.

The two biggest areas that I wish would improve with the existing ws:// transport are 1) ability to multiplex sockets based on URI resource (effectively, which could replace TCPmux), and 2) TLS for wss://

[mangos](https://github.com/gdamore/mangos) has some really cool features, and I would use it, but it's strictly limited to applications developed in Go. Ideally, its abilities could be ported to a C or Rust implementation, whose calling conventions are interoperable across most platforms and through most language's FFIs.

**Comment by gdamore** [comment]
This is not really an "issue" as such, although one could argue it would be nice if we could support websocket over HTTP/2, the lack of any standard for this (and the very newness of HTTP/2 itself) means we cannot proceed.

I'm closing this issue for now.  When/if a standard for websocket over HTTP/2 emerges, we should reinvestigate.  My suspicion is that libnanomsg will *never* support it, because the effort to support the full HTTP/2 protocol, as well as (really) full websocket semantics, is simply misaligned with libnanomsg's other goals.

If you need HTTP/2 for some reason, use mangos and a device.  (once mangos supports HTTP/2, which I guarantee will not occur before there is some kind of consensus for websocket over HTTP/2.  Which is not today.)

**Comment by reqshark** [comment]
what about a generic non-peer socket type? issue #397

**Comment by thelinuxlich** [comment]
For reference, something that builds on HTTP/2:

http://www.grpc.io/

**Comment by gdamore** [comment]
I’ve seen this.  It looks interesting, actually.  I’m not sure how you’d use it with nanomsg though.

	- Garrett

**Comment by thelinuxlich** [comment]
Actually I think it is a competitor

**Comment by gdamore** [comment]
Yes and no.  Nanomsg is just a transport not an rpc framework.   Req / rep patterns maybe "at risk" from the competition but nanomsg supports a variety of other useful patterns.

**Comment by robiwano** [comment]
I would rather see a possibility to use a nanomsg/nng used in a C code only gRPC service implementation, because there is no such thing today.
