### ISSUE TITLE
Change return type on send/recv routines to ssize_t

### ISSUE THREAD

**Issue by diffuse** [nanomsg/nanomsg#403]
Currently send/recv routines follow a similar pattern:

int nn_send (int s, const void *buf, size_t len, int flags);
int nn_recv (int s, void *buf, size_t len, int flags);

This seems problematic because a send can be done with size_t len.  It's counterpart (recv) can specify the receive length as a size_t length.  The problem I see is that nn_recv returns an int to specify how many bytes were received.  This may work for for 32-bit systems, but this would become an issue on 64-bit systems where int == 4 bytes and size_t == 8 bytes.

I have not tested the outcome of sending a file larger than 4GB, but it might make sense to modify nanomsg and change the return type of nn_send* nn_recv* messages to return a ssize_t or size_t instead of an int.

This change would align the nanomsg API calls close to socket.h api as well.

For example:
ssize_t send(int sockfd, const void *buf, size_t len, int flags);

**Comment by sustrik** [comment]
You'd have to deal with Windows somehow where ssize_t is not defined.

**Comment by diffuse** [comment]
We could conditionally define size_t on OSes that are missing size_t,

i.e.
#if WIN32
typedef SIZE_T size_t;
typedef SSIZE_T ssize_t;
#endif

**Comment by diffuse** [comment]
Would you agree this would be a good change to make?

**Comment by gdamore** [comment]
I'm of mixed minds.  Arguably, there should never be a need to support > 2GB of data in socket sends. (Nobody should do that!)  But ssize_t seems like the "right" fix here, and using a #define or typedef to work around windows limitations seems ok.

**Comment by djc** [comment]
Wouldn't size_t be better than ssize_t here? I'm +1 on the overall idea, though.

**Comment by diffuse** [comment]
The return type should be ssize_t because nn_send/recv need to be able to
return negative values on error.

**Comment by gdamore** [comment]
Its astonishing to me that ssize_t is not defined on any modern system.  That said, size_t works just cast the value of -1, which will probably 0xffffffff on 32-bit Windows, like this: (size_t)-1

All that said, who's ever going to try to pass > 4GB in a single nanomsg message?  That seems -- insane.  A number of platforms are going to have trouble dealing with such large payloads, and indeed to pass such a large message you'd need to allocate at least that much RAM, never mind the time it would take to transfer that much data (a 4GB message would take 312 msec to exchange over a dedicated 10GbE link running at wire rate.)  Never mind the fragility associated with this.

However, the protocol permits (over TCP) a 64-bit payload.  It seems "wrong" somehow that the library limits this.  However, I've found in practice to prevent DoS abuses/crashes, that it makes sense to apply a firm limit in mangos, which can be altered, but defaults to rejecting messages larger than a certain size (say 1MB).  I don't think libnanomsg applies any such limits (which arguably is a problem.)

**Comment by wirebirdlabs** [comment]
> However, I've found in practice to prevent DoS abuses/crashes, that it makes sense to apply a firm limit in mangos, which can be altered, but defaults to rejecting messages larger than a certain size (say 1MB). I don't think libnanomsg applies any such limits (which arguably is a problem.)

Agree with this. This, amoung a few other misbehaviors of remote endpoints, is a prime reason I would like to see a "close handshake" added to the nanomsg protocol to officially notify offending sockets the connection will be terminated. (here is one such conversation when developing WebSocket transport, since RFCC6455 defines a Close Handshake that could not cleanly map to nanomsg's lack of a close handshake: https://www.freelists.org/post/nanomsg/ws-transport,1)

The message size limit is a good idea for the reasons @gdamore outline; the Close Handshake is a good idea so that the remote endpoint does not observe radio silence when a too-large message is silently dropped by peer.

Introducing this new message type would break wire-level protocol with <=0.4 -- but breaking wire-level protocol is not nanomsg's key enemy right now!

**Comment by gdamore** [comment]
I'm not sure I understand what the point of transport level close hand shake would be.  Certainly, we *do* need a way to inform the core that an endpoint is gone/closed (and indeed mangos has this as well, including notification back to the *application* which is actually something useful that libnanomsg lacks), but what would the purpose to a wire-level change be, vs. an internal API change?

**Comment by wirebirdlabs** [comment]
> Certainly, we do need a way to inform the core that an endpoint is gone/closed (and indeed mangos has this as well, including notification back to the application which is actually something useful that libnanomsg lacks), but what would the purpose to a wire-level change be, vs. an internal API change?

My thought is the wire-level change would be just the addition of a new message type... but if you think this this could be handled without a new message type, and it seems proof of concept already exists in mangos, even better! (link to relevant mangos snippet: https://github.com/gdamore/mangos/blob/7e99876ea985abb5a94d52daefa0b5717b5cb66a/conn.go#L58-L61)

**Comment by gdamore** [comment]
I'm fairly confident that indeed, no wire protocol is necessary in any of the extant transports.  I'm not sure about the bottom half of websocket, but I guess those mostly get exposed through the API as "close" of the transport endpoint, which should be sufficient for the upper layer needs.

**Comment by gdamore** [comment]
In mangos we generally get a truncated read for the closed or disconnected peer.   Which is indeed sufficient, and we "properly" remove the endpoint and notify the upper layers.  This does mean that in order to detect the close that even sockets which have only send logic (e.g. pub, or push) need to have a passive reader notice the EPIPE/SIGPIPE error.

I'd have to look at libnanomsg more closely to see how it deals with this.  Running synchronous service threads and avoiding non-blocking I/O altogether is far easier in mangos/Go.  In vanilla legacy C, its a bit trickier.

**Comment by gdamore** [comment]
I'm inclined to leave this as is for now.  There isn't really any value in extending this to larger integer types at this point, as nobody is going to use nanomsg to transport messages larger than 2GB; the library would melt if that were tried.  And indeed, we have defenses in place to prevent it now.

Changing API signatures at this late date is probably also problematic, and see also the portability problems with ssize_t.

I'm just going to close this for now.
