### ISSUE TITLE
websocket assertion failed closing connection from browser

### ISSUE THREAD

**Issue by zakharov** [nanomsg/nanomsg#443]
Hello All,

Last month I was working on nanomsg websocket server and javascript clients. I mainly used two protocols REQ/REP and PUB/SUB. First one works fine. 

PUB/SUB gives an assertion error in
(line 134)
```
static void nn_xpub_in (NN_UNUSED struct nn_sockbase *self,
                       NN_UNUSED struct nn_pipe *pipe)
{
    /*  We shouldn't get any messages from subscribers. */
    nn_assert (0);
}
```
I traced the problem and discovered that the origin is in the state machine in sws.c. When closing socket in javascript client, state machine executes this part
(line 1449)
```
 case NN_WS_OPCODE_CLOSE:
                        /*  If the payload is not even long enough for the
                            required 2-octet Close Code, the connection
                            should have been failed upstream. */
                        nn_assert (sws->inmsg_current_chunk_len >=
                            NN_SWS_CLOSE_CODE_LEN);
                        
                        nn_sws_validate_close_handshake (sws);
                        return;
```
In nn_sws_validate_close_handshake function nn_pipebase_received (&self->pipebase) is executed, which propagates closing code to receive in XPUB and causes an assertion error. 

I also notices that nn_pipebase_stop is never called and socket is never removed.

Another problem happens when user is closing a browser client abruptly.

sws state machine goes to: 
(line 1219)
```
case NN_WS_OPCODE_CLOSE:
```

discovers that it needs to receive extended header+payload. In the next iteration it goes to:
(line 1315)
```
NN_SWS_INSTATE_RECV_HDREXT
```
where it goes to condition "Handle zero-length message bodies",
(line 1361)
``` 
if (sws->inmsg_current_chunk_len == 0)
 {
    if (sws->is_final_frame) {
      sws->instate = (sws->is_control_frame ?
      	NN_SWS_INSTATE_RECVD_CONTROL :
      	NN_SWS_INSTATE_RECVD_CHUNKED);
      nn_pipebase_received (&sws->pipebase);
      return;
    }
    else {
      nn_sws_recv_hdr (sws);
      return;
    }
  }
```
Here again nn_pipebase_received is called, which gives an assertion error in XPUB and socket is not removed.

As a quick fix for the first problem, I replaced 
```
nn_sws_validate_close_handshake (sws);
```
with
```
nn_pipebase_stop (&sws->pipebase);
sws->state = NN_SWS_STATE_CLOSING_CONNECTION;
```
In the second case, I added
```
if (sws->opcode ==  NN_WS_OPCODE_CLOSE)
{
   nn_pipebase_stop (&sws->pipebase);
   sws->state = NN_SWS_STATE_CLOSING_CONNECTION;
} 
```
These removed an assertion error and socket is been removed.

Of cause a closing code is not propagated to receive function any more, but I guess there should be another mechanism how to return it.

I hope this use case can help to improve nanomsg farther.

best regards,
Alexey

P.S : here is a very simple js subscriber to test this problem. Just try to reload the page or close it.
```
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title></title>
</head>
<body>
<script>
    function ab2str(buf) {
        return String.fromCharCode.apply(null, new Uint8Array(buf));
    }
    ws = new WebSocket("ws://127.0.0.1:5001", "pub.sp.nanomsg.org");
    ws.binaryType = "arraybuffer"; 
    ws.onopen = function() {
        console.log("opend");
    };
    ws.onclosed = function() {
        console.log("closed");
    };
    ws.onmessage = function(evt) {
        console.log(ab2str(evt.data));
    };
</script>
</body>
</html>
```

**Comment by wirebirdlabs** [comment]
Excellent analysis; thank you, @zakharov!

Your fixes seem rational solutions to an acute problem.

Back when the Close Handshake was [first being discussed](https://www.freelists.org/post/nanomsg/ws-transport,1), I was a proponent of formalizing a Close Handshake for nanomsg generally (i.e., for all transports, not just WebSocket).

If I recall correctly, the reason I decided to propagate the close handshake from the peer up to the application layer is because we were defining the close handshake as an app-layer concern, not transport or socket layer concern -- yet this clearly a problem when a PUB recv's a msg!

My understanding is the original nanomsg spirit set forth by @sustrik was to address the need for persistent, long-term and connections (the same spirit is why binding to an ephemeral port, although technically not so much a challenging feature to add, was specifically avoided, for good reasoning when applied to persistent service endpoints). For this reason, a Close Handshake perhaps didn't make sense to pursue. Yet I've found significant value in nanomsg connecting "short-lived, ad hoc" endpoints (e.g., actor-oriented development for embedded control and monitoring systems), where a Close Handshake would be helpful, and perhaps others are finding enough use here to gain traction.

Perhaps @gdamore can help further define this closing handshake protocol, perhaps in [terms of how mangos accomplishes this](https://github.com/nanomsg/nanomsg/issues/403#issuecomment-105994787)?

**Comment by zakharov** [comment]
In fact we are also using nanomsg for control and monitoring systems. What I couldn't figure out is a generic mechanism to inform an application layer that there is new connection/disconnection happened.

**Comment by wirebirdlabs** [comment]
> What I couldn't figure out is a generic mechanism to inform an application layer that there is new connection/disconnection happened

Out of curiosity, what logic would this be triggering at the app layer? Would it be acceptable to make `hello` and `goodbye` part of your app-layer protocol?

For the topologies you mention (PUB/SUB and REQ/REP), it might be best to consider the app-layer unaware of the connect/disconnect events themselves, since nanomsg intentionally tries to abstract this.

**Comment by gdamore** [comment]
When I need to know about client arrival and departure, I use application specific messages for arrival, and some kind of probe test message for departure.  With mangos you can also monitor for PortEvents().  Unfortunately libnanomsg has nothing like this at present.

The idea mostly is that applications should not worry about connected status.  If you’re going to manage that explicitly, it starts to look like nanomsg is probably not giving much benefit over plain old sockets.

	- Garrett

**Comment by gdamore** [comment]
Btw, will one of you be submitting a pull request for this?

	- Garrett

**Comment by zakharov** [comment]
Ok. I submitted pull request.

**Comment by zakharov** [comment]
>Out of curiosity, what logic would this be triggering at the app layer? Would it be acceptable to make >hello and goodbye part of your app-layer protocol?
>
>For the topologies you mention (PUB/SUB and REQ/REP), it might be best to consider the app-layer >unaware of the connect/disconnect events themselves, since nanomsg intentionally tries to abstract this.

"Hello and Goodbye" message from the client and its id. In my app clients subscribe for certain updates and sometimes do not unsubscribe properly in this case I would like to stop fetching data which nobody is interested in.  

Something like PortEvents(), which Garrett mentioned, would be great.

best regards,
Alexey

**Comment by gdamore** [comment]
Original assertion was:
src/protocols/pubsub/xpub.c:138

I'm editing this so that the synopsis fits on one line in commit. ;)
