### ISSUE TITLE
Significant refactor for a more sustainable libnanomsg?

### ISSUE THREAD

**Issue by JackDunaway** [nanomsg/nanomsg#445]
[Recently on the mailing list](http://www.freelists.org/post/nanomsg/inquiry-nanomsg-API), the topic of a significant refactor was discussed. Any developments, plans, or inclinations since then?

Specifically, [libuv](https://github.com/libuv/libuv) was identified by @sustrik as a candidate for abstracting some of libnanomsg's high-barrier-to-entry aspects of debugging/developing _(e.g., cross-platform async I/O and threading)_, repeated again [in a comment](http://250bpm.com/blog:50/comments/show#post-2314711) on his blog post _(this post which is one key inspiration in my uptick in energy to re-invigorate nanomsg)_.

@sustrik, would you support moving forward with libuv over other choices?

And @gdamore, putting you on the spot here too: do you think libuv specifically is a good basis for suggested [1-2wk](https://github.com/nanomsg/nanomsg/issues/432#issuecomment-122111431) hackathon?

If starting with TCP as the most general transport, and perhaps choosing REQ/REP, PUB/SUB, and PUSH/PULL as some of the more "popular" SP topologies, I would (and probably others as well) reasonably start to transition production code to help test and contribute.

It feels like nanomsg already has a critical mass, but we're still lurkers, and on the cusp of becoming active users/contributors/promoters. The activation energy put into an approachable architecture would enable us to help each other reach 1.0 sooner, and landing there with a more sustainable product. Such energy would also spur finalization of protocols to ring-out any breaking changes prior to 1.0, now that many of us have been using nanomsg for a while.

Anyone else following along at home having similar feelings?

**Comment by zakharov** [comment]
+1

**Comment by jbulow** [comment]
+1

**Comment by mguijarr** [comment]
+1

**Comment by reqshark** [comment]
+1

libuv's eventloop, or maybe [ae](http://redis.io/topics/internals-rediseventlib)

**Comment by gdamore** [comment]
I looked at libuv.  I'm not a fan of event loop programming and an unlikely to take that approach.  That shouldn't stop anyone else who wants to have a go though.

**Comment by gdamore** [comment]
Just to expand on my last reply.  I think event loops lead you down to state machine hell.  I implemented mangos using simpler imperative style programming and I'm happy with the end result.  So I'm more likely to try to copy that design.

**Comment by reqshark** [comment]
that's interesting. hadn't thought about it in those terms. 

low level event loop programming is much context/reference passing... it's a valuable exercise, because it makes one appreciate normal return values

**Comment by wirebirdlabs** [comment]
> Just to expand on my last reply.  I think event loops lead you down to state machine hell.  I implemented mangos using simpler imperative style programming and I'm happy with the end result.  So I'm more likely to try to copy that design.

Another view: incidentally, libuv architecture is event-driven callbacks, but fundamentally, it's an abstraction of Hard Problems dealing with async, cross-platform I/O.

Go provides the abstraction of this problem for mangos, and does it well. Though, to be fair... Go is currently not yet ready (as of pre-release 1.5, Q3 2015) for building native binaries with C calling convention. In other words, not yet able to speak lingua franca interoperable with <insert-your-language-du-jour-here>, it's unfortunately not as accessible as C.

I'm totally with you that Go channels provide a more elegant async solution while feeling imperative, but inverting dataflow to a callback might be a concession worth considering. In regards to "state machine hell", libuv manages/abstracts much of the state currently managed by libnanomsg, so the number of layers would be significantly reduced, making this concession not hurt too much. If anything, it would even be exciting to have this inversion at the library layer, such that language bindings could inject their own callbacks to provide idiomatic channels native to their language!

**Comment by reqshark** [comment]
> it would even be exciting to have this inversion at the library layer, such that language bindings could inject their own callbacks to provide idiomatic channels native to their language!

I agree. all of node.js' system i/o uses the libuv state machine `handles` so when binding to libnanomsg from node, it was was a natural (practically idiomatic) implementation fit to defer to that library to manage the need for a cross-platform I/O multiplexing strategy. 

Having such a consistent and complete async interface available between calls to `nn_recv()` or `nn_send` is necessary to do this right for node.js. And doing that gave us unexpected results in terms of where we were on network performance. Nanomsg AF_SP sockets over TCP gave us more than an order of magnitude higher performance when comparing equal buffers exchanged over Node.js' `net` library.
*<sub>if anyone is interested in verifying and measuring these results, checkout the `perf` pkg on npm or [this github repo](https://github.com/reqshark/perf)</sub>*  

So ya pretty good stuff and @wirebirdlabs, you might be interested to peek at our libuv implementation: https://github.com/nickdesaulniers/node-nanomsg/blob/b60a5130f7acbc03bacba57faf33212f88d0194a/src/node_nanomsg.cc#L226-L330 



if you do end up taking a look there, just try to avert your eyes from all the ugly C++ surrounding it. Don't mind the weird pointer casts, the use of calloc or other unmentionable things needed in order to pass socket descriptor state information back and forth between libuv, JS and nanomsg... we do those extra context switches into the JavaScript language as a tradeoff for being able to reason about when to give and get data/buffers in JS land back and forth across the nanomsg SP protocol backend

**Comment by gdamore** [comment]
We won't be using libuv unless someone else wants to do the work.  That would create different C++ requirements.  I'm also not keen to create another event driven monstrosity.  Current architecture uses event loops and finite state machines to drive everything, and has led to the current mess.

A refactor, should I undertake one, will change a number of constraints.  This may make it a poor drop-in replacement (or not a drop-in at all) for libnanomsg.  The constraints I'd change are:

a) Eliminate POSIX API compatibility.  The code is vastly more complicated because of attempts to make sockets select()'able.  And even integer descriptors add complexity.  Easier to just pass around state pointers.  But more to the point, not having to create a separate poll() loop ,or go through the ridiculous contortions done on Windows to make WSAselect() work.   (Many of the windows bugs derive from this goal.)

b) Relax portability requirement somewhat.  In particular, I'm likely to require modern threading primitives.  Creating tasks, and running low level I/O in blocking modes is frankly far safer, and ultimately more portable.  And gets us out of FSM hell.

c) Narrower internal APIs, with less attempt to "share implementation" between transports.  Especially Windows and POSIX shouldn't try to share code here -- the hodge podge of .inc files is bad design.  Better to design narrow transport provider APIs, and let those transport providers implement to them directly.

Much of this design will look like mangos.  HOWEVER, I will not plan on using libmill.  I feel libmill is going the wrong way -- still trying to "fake out" concurrency using hackery, instead of just relying on reasonable platform threading APIs.

This approach may make whatever the new refactor is called far less suitable for use in embedded environments; and it may make it harder to embed in language run times (I'm not sure about that).  Threading and fork() are particularly challenging to deal with in combination.  But I think getting that right will still be far easier than what we've got now.

**Comment by reqshark** [comment]
> We won't be using libuv unless someone else wants to do the work. That would create different C++ requirements.

libuv is written in C.

> I feel libmill is going the wrong way -- still trying to "fake out" concurrency using hackery

Concurrency by message passing is real. Sending messages over co-routines may avoid context switches into kernel space (syscalls) we otherwise incur using the thread and mutex. 

> instead of just relying on reasonable platform threading APIs

Reasonable to me means selecting the best possible concurrency model for the situation. I wouldn't rule out Libmill on the basis of its ability to provide a meaningful concurrency framework for Linux and OS X. IMO, lack of windows support is the reason to reject it (if we're talking about `nn_thread_routine`)

**Comment by gdamore** [comment]
I'm closing this for now--- libnng *is* happening, and is basically a rewrite from scratch.  I am using threads, but the platform layer is sufficiently flexible that if someone wants to use libmill or libuv or some other framework, they can do that.  They just need to be able to express "threads" logically (which could be coroutines) and some other typical primitives (mutexes, condvars, related network operations, etc.)

**Comment by mguijarr** [comment]
Thanks for the great work.
