### ISSUE TITLE
dns resolver fails when more than result returned

### ISSUE THREAD

**Issue by nickdesaulniers** [nanomsg/nanomsg#457]
[this block](https://github.com/nanomsg/nanomsg/blob/master/src/transports/utils/dns_getaddrinfo.inc#L104-L112) is [causing failures downstream](https://github.com/nickdesaulniers/node-nanomsg/issues/107) for a user.  I'm not sure why having more than one address get resolved is considered an error, or how more than one is returned in the first place.

**Comment by gdamore** [comment]
Yeah, that's bogus.  More than one gets returned in configurations with IPv6 and IPv4, or when the site admin tries to set up multiple addresses for load balancing and failover.

Its pretty lame, this needs some thought. 

To be honest, I *HATE* that libnanomsg does its own DNS lookups.   In my own applications I always resolve names outside of the library, so that I have control over when the resolution happens, and dealing with things like policy, multiple port binding, failover, etc.

**Comment by gdamore** [comment]
Can we just remove the assertion?

**Comment by bnewbold** [comment]
From RFC 3484 (http://www.ietf.org/rfc/rfc3484.txt):

"Well-behaved applications SHOULD iterate through the list of addresses returned from getaddrinfo() until they find a working address."

It looks like the `reply` is getting free'd immediately, and it would take a refactor to iterate through options.

I would support just going with the first address replied for now and opening a new issue as a task to re-implement the correct way.

**Comment by gdamore** [comment]
I'm going to remove the assert.  That will let this code move forward with minimum pain and suffering.

Folks that expect to use DNS to achieve round robin or some such with nanomsg - it isn't going to work. As with (I suspect! the vast) majority of apps, we're going to just take the first name we get and move forward with that.

Trying to do otherwise would require tying DNS a bit more tightly into the connection/failover logic.  This is wrong on *so* many levels, especially for nanomsg. 

Again, I strongly recommend using IPs with nanomsg, or at least ensuring that a single DNS record is returned and valid.
