### ISSUE TITLE
assertion failure in ipc_shutdown

### ISSUE THREAD

**Issue by europelee** [nanomsg/nanomsg#469]
Hi guys:
I run example tests/ipc_shutdown with the 0.6-beta version codes ( Ubuntu 14.04.3 LTS (GNU/Linux 3.13.0-32-generic x86_64)),
and sometimes it fails: 
src=0 type=33988
Assertion failed: src == NN_SOCK_SRC_EP && type == NN_EP_STOPPED (src/core/sock.c:839).
the analysis:
1.
ipc_shutdown.c already had signal(SIGPIPE, SIG_IGN); so it is not the problem(tcp_shutdown & ipc_shutdown failures (Solaris/illumos) #394).
2.
I found that nn_sock_shutdown solved the problem on the old version as the below:
    default:
        if (type == NN_PIPE_STARTED || type == NN_PIPE_IN || type == NN_PIPE_OUT) {
            /*  Silently ignore connection acknowledgement during shutdown.
                This is an infrequent, benign race condition when an endpoint
                async connection starts just before the bound endpoint is
                closed or zombified, and the connection succeeds while the
                socket is still shutting down (nominally, while other endpoints
                continue to shut down). srcptr should be a valid nn_pipebase. */
            nn_assert (srcptr);
            break;
but the current version why not?
instead:

   834     if (nn_slow (sock->state == NN_SOCK_STATE_STOPPING_EPS)) {
   835
   836         /*  Endpoint is stopped. Now we can safely deallocate it. */
   837         if (!(src == NN_SOCK_SRC_EP && type == NN_EP_STOPPED)) {
   838             fprintf (stderr, "src=%d type=%d\n", (int) src, (int) type);
   839             nn_assert (src == NN_SOCK_SRC_EP && type == NN_EP_STOPPED);
   840         }

**Comment by wirebirdlabs** [comment]
> I found that nn_sock_shutdown solved the problem on the old version as the below ... but the current version why not?

As the author of that code and comment, I later found this "patch" pushed the failure mode to other places which turned out to be harder to diagnose and perhaps fix. In other words, that change didn't help, and maybe even made things worse.

I didn't think this code/comment were mainlined, but if they were, it's good they're reverted.

**Comment by europelee** [comment]
Hi, I found the problem only happen when tested on virtual machine,
but when i add nn_sleep before test_close, then the problem was solved, as below:
    sb = test_socket (AF_SP, NN_PUB);
    test_bind (sb, SOCKET_ADDRESS);

    for (j = 0; j != TEST_LOOPS; ++j) {
        for (i = 0; i != THREAD_COUNT; ++i)
            nn_thread_init (&threads [i], routine, NULL);
        for (i = 0; i != THREAD_COUNT; ++i)
            nn_thread_term (&threads [i]);
    }
    nn_sleep(200); // it solved the problem.
    test_close (sb);

but it is still needed a root cause analysis.

**Comment by gdamore** [comment]
ipc_shutdown:Assertion failed: src == NN_SOCK_SRC_EP && type == NN_EP_STOPPED (src/core/sock.c:839)

(shortening title)

**Comment by gdamore** [comment]
So my change didn't fix this -- that was *another*, different problem.  Aargh.

Looking carefully at this section of code, I think the problem is that we can have two different threads enter this section of code for two different endpoints, and they can race.

This makes sense with the shutdown call, because that test has lots of endpoints against a single socket.

I'm reasonably confident that this race is solvable.  We really need to use reference counters here to ensure that things are safe...  stay tuned.

**Comment by gdamore** [comment]
My analysis is that what is really happening isn't a thread race, but multiple events probably occurring due to multiple FSM events pending on the socket.   In this case, if the socket is waiting for cleanup, we cannot really do anything else until the EPs are done cleaning up.  So my solution is to just bail, and let the EPs do the cleanup when they enter this logic.  Here's the proposed diff (under stress testing now):

```
--- a/src/core/sock.c
+++ b/src/core/sock.c
@@ -833,11 +833,14 @@ static void nn_sock_shutdown (struct nn_fsm *self, int src, int type,
     }
     if (nn_slow (sock->state == NN_SOCK_STATE_STOPPING_EPS)) {

-        /*  Endpoint is stopped. Now we can safely deallocate it. */
         if (!(src == NN_SOCK_SRC_EP && type == NN_EP_STOPPED)) {
-            fprintf (stderr, "src=%d type=%d\n", (int) src, (int) type);
-            nn_assert (src == NN_SOCK_SRC_EP && type == NN_EP_STOPPED);
+            /*  If we got here waiting for EPs to teardown, but src is
+                not an EP, then it isn't safe for us to do anything,
+                because we just need to wait for the EPs to finish
+                up their thing.  Just bail. */
+            return;
         }
+        /*  Endpoint is stopped. Now we can safely deallocate it. */
         ep = (struct nn_ep*) srcptr;
         nn_list_erase (&sock->sdeps, &ep->item);
         nn_ep_term (ep);
```

**Comment by gdamore** [comment]
(The tests ran well over night.)
