### ISSUE TITLE
interface/address issue prevents bind/connect

### ISSUE THREAD

**Issue by reqshark** [nanomsg/nanomsg#506]
confirmed connect and bind failures on iOS platform, also reported tonight on Windows

msgs over TCP/WS have failed silently/inconsistently after updating to beta 7, but we've pinpointed the issue thanks to @jl777 reporting with @gdamore discussion in [nanomsg gitter chatroom](https://gitter.im/nanomsg/nanomsg).

The problem for me on iOS resolves immediately by reverting
```git
commit a896c3051f1b8a0da4fd92819cca9f102dd610e2
Author: Garrett D'Amore garrett@damore.org
Date: Sun May 31 14:17:08 2015 -0700
fixes #371 Assertion failed: !ipv6 (src/transports/utils/iface.c:88)
```

 accordingly here's #507 submitted under the project's MIT license

**Comment by gdamore** [comment]
This cannot happen on Windows (no named interface names, so they can't use this functionality at *all*), and is probably an issue with ipv6 on MacOS too.

**Comment by reqshark** [comment]
yes, but i'm finding it odd that OSX would be unaffected, versus the breaking iOS behavior

**Comment by gdamore** [comment]
But I doubt OSX is unaffected.  I *do* think people don't see it on OSX because home users rarely configure IPv6.

**Comment by reqshark** [comment]
@gdamore it's not easy to reproduce. The error is inconsistent and most of the time it works as expected.

I was looking at two scenarios over IPv4 localhost, i.e. msgs sent over an address of `127.0.0.1:5555` and connecting to a publishwe on my local network, so that was an address of `10.0.1.2:4444`

**Comment by gdamore** [comment]
I want to see the specific address you’re using — maybe just cut and paste
the nn_connect() and nn_bind() calls.

That said, the inconsistent nature of your error, along with *other*
incorrect code I’ve seen you send (off-by-one string handling) makes me
wonder if this code is not just falling victim to heap corruption caused by
an error somewhere else in your code.  I can completely believe that heap
errors could cause all kinds of grief, most of which would be difficult or
impossible to root cause.  (This is the nature of heap errors.)

I’m not sure you have debugging allocators available to you (particularly
ones with red-zone areas, e.g. the ability to detect writes beyond the
allocated area, use after free, etc.), but if you do, you might want to run
your code through it.

There is almost no conceivable way that nn_resolve_literal() can fail
non-deterministically.  It makes no use of shared state, and is simply
parsing the string.  If this is failing “randomly”, then something else
somewhere else is going very wrong.

**Comment by reqshark** [comment]
> I’m not sure you have debugging allocators available to you (particularly ones with red-zone areas, e.g. the ability to detect writes beyond the allocated area, use after free, etc.), but if you do, you might want to run your code through it.

I'm using apple's LLDB to detect any bad memory access

> just falling victim to heap corruption caused by an error somewhere else in your code. 

that could be what's going on, at any rate, here's my iOS connect code:

```objective-c
#include "nn.h"
#include "tcp.h"
#include "ws.h"
#include "pubsub.h"
#include "sleep.h"
#define ADDR "ws://10.0.1.2:4444"

  int s = nn_socket (AF_SP, NN_SUB);
  
  int r = nn_setsockopt (s, NN_SUB, NN_SUB_SUBSCRIBE, "", 0);
  if(r > -1){
    printf ("subscriber socket set\n");
  } else {
    printf ("error setting subscription socket: %d\n", r);
    // return 1;
  }
  
  //bind and connect sockets
  nn_connect (s, ADDR);
  nn_sleep (10);
```

another machine with public address `10.0.1.2` publishes websocket msgs over 100ms interval, and it's working fine, they're all being received as expected.

close the issue if you like, but i'd like to keep it open in case I repro at some point later on this week

**Comment by gdamore** [comment]
I can't close it, because its still broken for named interfaces.  All you've proven is that as I said, if you use IP addresses, it works, which is the workaround I've given.
