### ISSUE TITLE
stop maintaining full downloads page

### ISSUE THREAD

**Issue by gdamore** [nanomsg/nanomsg#512]
github releases does this for us.  Maintaining a download page with links to historical releases really offers ~0 value, and adds complexity to the RELEASING process.  We should just put a link into the github releases page, and change the RELEASING document to remove that step.

**Comment by reqshark** [comment]
changing those URLs could cause build system breakage if people are depending on a different URL address format

**Comment by gdamore** [comment]
Unless someone is screen scraping the HTML— but if they’re doing that in a
build system, they deserve what they get.

I’m not changing the actual URL — in fact gh releases API is far better to
use here.  Just the download page.

**Comment by reqshark** [comment]
yea looks like you've been doing this since beta-06 anyway the URL links are,

https://github.com/nanomsg/nanomsg/releases/download/0.7-beta/nanomsg-0.7-beta.tar.gz
https://github.com/nanomsg/nanomsg/releases/download/0.6-beta/nanomsg-0.6-beta.tar.gz
http://download.nanomsg.org/nanomsg-0.5-beta.tar.gz
http://download.nanomsg.org/nanomsg-0.4-beta.tar.gz
... etc
