### ISSUE TITLE
tcpmux daemon returns -1 on iOS

### ISSUE THREAD

**Issue by reqshark** [nanomsg/nanomsg#514]
stepping through the code it looks like it's caused by this line: https://github.com/nanomsg/nanomsg/blob/master/src/devices/tcpmuxd.c#L119

```c
rc = bind (ipc_listener, (struct sockaddr*) &ipc_addr, sizeof (ipc_addr));
```
these are the values I have so far at that breakpoint:

`port`	int	5555	5555
`rc`	int	-1	-1
`ipc_listener`	int	7	7
`ipc_addr`	sockaddr_un		
`sun_len`	unsigned char	'\0'	'\0'
`sun_family`	sa_family_t	'\x01'	'\x01'
`sun_path`	char [104]	"/tmp/tcpmux-5555.ipc"

not sure if it has something to do with unlinking the fd path right before bind():
https://github.com/nanomsg/nanomsg/blob/master/src/devices/tcpmuxd.c#L113

**Comment by reqshark** [comment]
IPC may not be supported out of the box on iOS. After doing a little research I found:

*  `unlink()` before bind is actually the idiomatic approach to IPC
* apple iOS restricts file permissions, like read/write to the app's private directory

**Comment by gdamore** [comment]
I really wish people wouldn't use tcpmux.  Its experimental from Martin, and I think problematic in many regards.  Its also not portable.

And yes, on platforms where you need IPC to work.  I'm probably going to close this as Will Not Fix, because I have no idea how to make IPC work on iOS.

The unlink before bind() is actually not a great idea universally, and is definitely not what I'd call idiomatic.  Its a hack to ensure that if an earlier application crashed without cleaning up the name, that the name is available for use in a new instance.  HOWEVER, it causes severe problems if you have multiple instances of the app running.

What's actually required here is you have to test if your old application is still present, and if it is, fail cleanly, usually.  The unlink() should only be called when you've ascertained beyond any doubt that it is safe to do so (i.e. no other application is actually using the name, and the name isn't problematic for other reasons -- e.g. a real file posted somewhere.)

Anyway, as I said, I'm not going to fix tcpmux for iOS.

**Comment by reqshark** [comment]
thanks for the info on unlink before bind! That's good to know.

won't fix is understandable POSIX IPC has been completely warped on iOS. However, it is indeed possible to make it work
