### ISSUE TITLE
Design consideration for protocol violation

### ISSUE THREAD

**Issue by wirebirdlabs** [nanomsg/nanomsg#555]
While working on fixing #551 and reconsidering the behavior of how the WebSocket transport responds to a peer that violates the expected protocol based on SP and transport expectations, I got to thinking about the fix for #443 (cc: @zakharov for visibility).

At the time, I agreed with the fix provided by @zakharov to avoid the assertion -- but now, it seems that this fix is only skirting a more fundamental problem.

The fundamental problem is this -- a "peer" could intentionally, or unintentionally, violate the expected protocol of any given socket semantics.

The current behavior of libnanomsg in such protocol violation in many places is to throw an `nn_assert()` -- as was the problem with case #443, which hit the assertion here since XPUB never expects a peer to send a message: https://github.com/nanomsg/nanomsg/blob/master/src/protocols/pubsub/xpub.c#L138

The fundamental problem with throwing an assertion is that the assertion is not providing a guarantee of self-integrity within the libnanomsg library, but instead, it's a gaping security hole.

As a perfect example, #443 discovered this security issue during the standard-operating-procedure of a browser.

**Proposal**: the transport layer needs to be able to provide a formal manner of failing the connection in a sane manner when a peer violates the protocol, where the failing of this connection can be invoked by the scalability protocol layer if its contract has been breached.

With such a definition, #443 could be reimplemented with a more robust fix, rather than the current fix that simply avoids a specific problem.

(Related security/robustness discussion about NN_RCVMAXSIZE on: https://github.com/nanomsg/nanomsg/issues/461 and http://www.freelists.org/post/nanomsg/issue-with-received-message-size,1)

**Comment by gdamore** [comment]
I agree that we must not crash in the face of protocol violations but instead drop the connection.  Logging it or bumping a stat is also a good idea.  I use this approach in mangos as I designed it to be robust from day one.  Libnanomsg was sadly not designed with any thought to security or robustness in the face of malicious peers.  This is something we need to fix. 

That said the fix for #443 was correct for that bug.  However we should ALSO have the mechanisms you propose here in the various places in the code. 

I'd like to go through and audit all the assertions in the code at some point.  Asserting on content sent to you by a peer is WRONG.  The use of asserts should be restricted exclusively to conditions contained within the address space and under absolute control of the library to ensure. 

A corollary to this is that there should be a lot fewer assertions combined with more robust runtime protocol validation.

**Comment by gdamore** [comment]
I'm closing this -- we agree on the design principles -- but until we have specific issues -- presumably uncovered by a full code audit or extensive testing, there isn't a specific deliverable here.
