### ISSUE TITLE
Dolt breaks libtool PIC options

### ISSUE THREAD

**Issue by Snaipe** [nanomsg/nanomsg#588]
Currently, the Dolt macros completely break the behaviour of libtool PIC options (`--(with|without)-pic` and `pic-only`). This makes it impossible to link the static nanomsg library into shared libraries.

(I remember discussing with @gdamore on gitter that the autotools build system was to be replaced by cmake on all platforms eventually, so I'm not sure if I should submit a patch for dolt.m4)

**Comment by wirebirdlabs** [comment]
Hi @Snaipe -- I don't have an answer, but can offer some related information.

When working on bringing CMake chain up to the same capability as the Autotools build chain, I noticed something similar -- that nanomsg was not yet designed to switch back/forth to shared/static library at the configuration stage.

Here's a commit that fixes this for Windows: https://github.com/wirebirdlabs/featherweight-nanomsg/commit/ce4c5d353b9e22f4e7f0e7620095724cc72c8b61

That said, would you be willing to switch to CMake instead of Autotools and submit any patches there? If so, I would greatly appreciate your help so we could mainline that work. Here are more details: https://github.com/nanomsg/nanomsg/issues/574

And here's a preview of the CMake script: https://github.com/wirebirdlabs/featherweight-nanomsg/compare/pr-ws-mega-squash...wirebirdlabs:ftw-kernel#files_bucket

**Comment by Snaipe** [comment]
This seems fair. A CMake setup would be easier to deal with on my end, so I see no issue switching to it at the moment.

**Comment by wirebirdlabs** [comment]
Cool! What is your timeline for needing this? I will try to create a cogent PR within the next couple days that puts together this CMake work, from which you can work.

If you want to start before that, feel free to cherry-pick and continue making forward progress, but be forewarned that the PR will have squashed most of those commits into a single commit (meaning, if you work from these, your branch wouldn't cleanly fast-forward from what would eventually be mainlined, though your work should be able to be cherry-picked cleanly onto mainline)

**Comment by Snaipe** [comment]
I can wait a couple of days, no worries.

**Comment by gdamore** [comment]
So definitely we're gonna do CMake.  Probably this can be closed when we have it.

**Comment by gdamore** [comment]
Initial cmake work is done, and we're moving towards that as fast as we can.  I'm closing this issue as "WILL NOT FIX" -- because just use cmake. :-)

**Comment by JackDunaway** [comment]
See: https://github.com/nanomsg/nanomsg/issues/648
