### ISSUE TITLE
Got time_wait after client stop

### ISSUE THREAD

**Issue by taolinke** [nanomsg/nanomsg#592]
Thanks for your reading.
When the client ends, it revoke 
nn_shutdown(fd, eid);
nn_close(fd);
but i still got the TIME_WAIT, no matter set NN_LINGER to 50 or 0.
Is there any way to avoid it?

**Comment by taolinke** [comment]
My platform is centos 5.9, kernel is linux 2.6.18_x64

**Comment by taolinke** [comment]
i have solved the problem by changing the source of src/aio/usock_posix.inc.
if anyone who want the change. tell me.
my email is zz1126wnx@gmail.com

**Comment by zhaozg** [comment]
Hi, may you give a PR for this

**Comment by taolinke** [comment]
老赵.....

**Comment by zhaozg** [comment]
熟人，哪位啊

**Comment by taolinke** [comment]
@zhaozg 张钊....，PR是什么东东，不知道哎

**Comment by zhaozg** [comment]
pull request 就是给个git的补丁 比在大街上碰到的概率要高啊 就不在这儿沟通感情了

**Comment by reqshark** [comment]
Yes but I thought linger was designed to be only a simpler interface to UNIX socket option SO_LINGER:

> When enabled, a close(2) or shutdown(2) will not return until all queued messages for the socket have been successfully sent or the linger timeout has been reached.  Otherwise, the call returns immediately and the closing is done in the background.

> When the socket is closed as part of exit(2), it always lingers in the background.

**Comment by wirebirdlabs** [comment]
> pull request 就是给个git的补丁 比在大街上碰到的概率要高啊 就不在这儿沟通感情了

Also, to simply make it easier for @taolinke -- if the change you made is pushed to your own public fork of the nanomsg repository, a nanomsg repository owner will be able to cherry-pick your work with your permission (maintaining your attribution to the commit). The goal here is to lower the barrier for upgrades to the library, and not let git or GitHub be a barrier to those upgrades. I'd be interested to evaluate this change for my own branch, even if it doesn't make it into the trunk.

**Comment by gdamore** [comment]
Just turning off linger is a bad idea. 

The reason is that the default is to let the OS finish delivering messages that are queued for delivery after exit. Disabling this means instead your messages will be dropped.  Note that this is after the write() or sendmsg() has returned. 

If you think you need this, then I suspect you are doing something wrong. TIME_WAIT exists for a good reason; if your client stays alive long enough to finish the delivery then exiting should not cause this behavior. 

It sounds to me like you are doing a tx and then exiting. 

Try waiting a bit, or even INCREASING the linger to give nanomsg a chance to complete the delivery before you call nn_close and do make that call before you exit. 

If I were still maintained I'd reject any change to the default linger behavior.

**Comment by anJava** [comment]
@zhaozg :你好，在么，我是上海的一个刚工作的程序员，看到你上传了openscep的代码， 我想安装openscep服务，可是安装不上，想请教一下，这是我的qq：870963566，非常感谢！！

**Comment by zhaozg** [comment]
@anJava 请不要在这里讨论与 nanomsg 无关的问题, 另外关于 opensecp 表示抱歉, 因为我还没有开始具体的研究， 你可以到 https://github.com/zhaozg/openscep/issues 这里把碰到的问题贴出来，也许无法対你的问题作出理解响应，但是我有时间的化 回去看一下的
