### ISSUE TITLE
There are a reason why NN_MSG is not included in nn_symbols? 

### ISSUE THREAD

**Issue by niwinz** [nanomsg/nanomsg#602]
The https://github.com/nanomsg/nanomsg/blob/master/src/core/symbol.c file does not includes it so it can't be obtained using nn_symbol function.

**Comment by gdamore** [comment]
Well, yes.  NN_MSG is not an integer symbol, but a size_t (and -1), so you can't reliably express its value in an int.

Furthermore, I can imagine *no* reason why you'd ever want to express this to an alternate runtime -- this isn't a value that applications that can't access the C type directly should ever use, since it affects how libnanomsg behaves with respect to memory allocations and buffers.  (So for example, it would be tragically bad for a language binding to give this option to applications, unless the binding included explicit handling for it.)

This is quite unlike other things like socket options, address family or domain, or errnos where applications can reasonably change behaviors without requiring the language binding to take any special action.

I won't be exposing this via nn_symbol() as a result.
