### ISSUE TITLE
nn_tcp_keepalive_time or nn_tcp_keepalive_intvl socket option

### ISSUE THREAD

**Issue by reqshark** [nanomsg/nanomsg#614]
I think keepalive may be useful as NN_TCP option, probably not NN_SOL_SOCKET, but something like:
* `nn_tcp_keepalive_time` or could be like:
* `nn_tcp_keepalive_intvl`

Idea based on linux `sysctl` interface to avoid upfront wakeup time and latency associated with long waiting intervals before next msg recv.

**Comment by gdamore** [comment]
Why do you think keepalive has anything to do with wakeup?

Keepalives are handled in the kernel generally, and do not pass up to the application.  Their purpose is to ensure that a minimal amount of traffic is seen on otherwise idle TCP connections.  This is often necessary to keep things like stateful firewalls or NAT from misdiagnosing such connections as stale and dropping them.  The other reason is so that the far end of a connection can detect a dead peer -- triggering a little bit of protocol to act sort of like a heartbeat on the TCP connection itself.

I've rarely seen a useful case for tuning the keep alive interval, to be honest; usually the case is to help the far end of a connection notice a dead peer earlier; this is necessary on very high volume servers to ensure that stale TCP connections are reaped.  (A similar reason why firewalls and NAT devices clean up idle connections -- its about resource management really.)

**Comment by reqshark** [comment]
when msgs are few and far between endpoints, low latency delivery between send and recv I/O is ideal.

> Why do you think keepalive has anything to do with wakeup?

I use the term wakeup to describe additional time spent recognizing the need for I/O, for long running idle subscribers. In that case, I've used an interval of small sz msgs to reduce what I call wakeup latency

> Keepalives are handled in the kernel generally, and do not pass up to the application. Their purpose is to ensure that a minimal amount of traffic is seen on otherwise idle TCP connections.

While that sounds very efficient to me, I would be willing to sacrifice resources required to process additional traffic on an otherwise idle TCP connection, if that is the cost of immediate transport I/O for the rare and infrequent msg recv--IMO a suitable resource allocation and expense.

**Comment by gdamore** [comment]
So you're talking about an application layer heartbeat because normal TCP keepalives don't do what you want (mostly; there is some cache warmness in the kernel but the app never wakes up to process these). 

That sounds like a new message type. I'm not in favor of this. It would add substantial complexity to libnanomsg (more state machines!!) for a very limited benefit to a tiny set of applications. 

Better if your app needs this that you do a heartbeat in the application code itself - eg another req/rep message or a periodic pub or somesuch.  Far less complexity and risk, and easy to do for you particular app.

**Comment by gdamore** [comment]
Btw what are your latency requirements?

Outside of context switch induced delays (which can be solved easily using tasksets to bind to specific cores), I find the worst case TCP latencies for single messages to be well under 10us on decent network gear with properly tuned drivers and NIC.  And yes this is general purpose OS - either Linux or illumos. 

A bigger concern is making sure that both TCP Nagle is disabled and any interrupt moderation at the NIC is turned off. The former can add a number of milliseconds if mistuned. The latter adds about 30us on typical 10GbE.

**Comment by reqshark** [comment]
> Better if your app needs this that you do a heartbeat in the application code itself

well yeah, that's what i end up doing.

> ..making sure that both TCP Nagle is disabled and any interrupt moderation at the NIC is turned off.

I set tcpnodelay option for the use case, but I didn't know about *interrupt moderation at the NIC*.. I'm going to have to do some research now.

> Btw what are your latency requirements?

Unfortunately, we deploy across today's lowest performing networks.. often deep into last mile DSL

So while writing said interval solves the application problem well, I thought my user land experience might be common to a few others, and without question improved by a library socketopt. 

> sounds like a new message type. 

I disagree, I think it's a TCP transport option.

> I'm not in favor of this. It would add substantial complexity

let's not add complexity to an area already rife with it, I'm just about ready to drop the issue, unless other people using the library might find it useful too.

**Comment by gdamore** [comment]
The problem with this being a TCP transport option is that TCP doesn't actually do this.  It does have TCP_KEEPALIVE, but that doesn't do what you're talking about; it's for something else entirely.

That said, there may be considerations in keeping *mobile* devices from going to sleep.  (I wonder though, is it really the right thing to do to prevent a client device from sleeping or going into lower power state?  I know that I wouldn't want any of the apps on my phone or computer to do that!  If they don't have anything to do and my device is sleeping, then I'm not going to notice a few tens, or even hundreds, of milliseconds of additional latency to wake the device up.)

Your application layer heartbeat is still the right place to do this, if you have a desire to keep an application up and running -- but really there are still better ways to do this, such as binding the app to cores, and increasing its scheduling priority (see nice(1)).

I'd suggest you go ahead and close this -- I'm not maintainer anymore, so I'd leave it to you to do so.

**Comment by reqshark** [comment]
thanks @gdamore!
