### ISSUE TITLE
Project appears to be unmaintained, take care

### ISSUE THREAD

**Issue by saulthu** [nanomsg/nanomsg#619]
Sady this project appears to be unmaintained. See:

http://www.freelists.org/post/nanomsg/Dead,5
https://news.ycombinator.com/item?id=11057550
http://sealedabstract.com/rants/nanomsg-postmortem-and-other-stories/

**Comment by gdamore** [comment]
I'm willing - reluctantly - to come back and work on this stuff again. However if I do so then it will be as a dictator to run the project by edict rather than by consensus. That is I may seek opinions but I would not feel compelled to adhere to them. 

I believe that this project cannot survive in consensus mode.

However I won't come back unless the other folks with git access agree for me to do so under precisely those terms. 

To be clear this was never my intent and I would have preferred to see someone else competent step forward. But that hasn't happened.

Note that none of this affects licensing - the code must always be released under the same license as I don't own nor do I want to exclusive ownership in the code. So the freedom to fork will always be there for anyone who needs it.

**Comment by wirebirdlabs** [comment]
I support the proposal by @gdamore as BDFL and would likely ramp up again as a contributor if this happened.

**Comment by mojoTX** [comment]
I'm working on a commercial product, and we're seriously considering using nanomsg as our core messaging platform. Naturally if we did use the library, we would actively contribute back, but the lack of activity was one of our concerns.

It's been my observation that most successful open-source projects DO have a strong "BDFL" type leader that delegates as needed.

**Comment by gdamore** [comment]
Officially, I'm back as maintainer now.  I'll ramp up myself, and this will take a little bit (but not too much I hope) time.
