### ISSUE TITLE
Unix domain socket files not unlinked when closed

### ISSUE THREAD

**Issue by Snaipe** [nanomsg/nanomsg#666]
IPC sockets on linux doesn't seem to unlink the socket file when the nanomsg socket is closed/terminated.

This is consistently happenning for all IPC tests.

Tested on Linux 4.4.5-1 (ArchLinux) and Linux 3.13.0-85 (Ubuntu 14.04).

**Comment by gdamore** [comment]
That's correct.  There is no "correct" way to handle socket removal as there can be multiple participants. 

Probably we could do removal if the socket was a listener. It's obvious that we should not do so for client sockets.

**Comment by JackDunaway** [comment]
The way this was effectively handled previously was using autotools: https://github.com/nanomsg/nanomsg/blob/master/Makefile.am#L587

Although the current behavior of leaving behind these artifacts is messy, there may not be any equivalent port from autotools to CMake.

That said, with CMake performing an out-of-source build, removing these and all other build/test artifacts is as simple as `git clean -xfdn` or `rm -rf build` from the project root.

Can you think of any actionable fixes for this issue?

**Comment by gdamore** [comment]
I don’t think the tests have a problem with this, because they rather
blithely just delete the file system nodes if I recall properly.  That’s
not necessarily a good solution for end users.

I’m thinking that maybe nn_close() of a listener socket should unlink the
filesystem nodes, but I’m not 100% sure that is the best solution or is
without pitfalls.  To be honest IPC sockets are fraught with problems
because of this, and I actually don’t know of any race-free solution to the
problem that is remotely portable.  (File system locks can do it, but
that’s got its own issues.)    This is why I stopped using IPC in
production myself, and only use loopback TCP in my products built on top of
nanomsg.

**Comment by Snaipe** [comment]
@gdamore unlinking the socket file after a listener closes is an accepted way of doing unix domain programming (some people do so before the bind() to avoid getting an "Address already in use", and I think this is what nanomsg is [currently doing](https://github.com/nanomsg/nanomsg/blob/8f873b454de981553e48137fbf32a41b4f36bb77/src/transports/ipc/bipc.c#L410)).

Now, I'm not a fan of leaving sockets files all over the place, because I'm currently using ipc to bind to "ipc://<name>_<pid>.sock" to allow multiple instances of my application to run in parallel (which after a few ctest runs floods the current directory with socket files), and without ephemeral port binding using a tcp transport wouldn't be as straight forward.
