### ISSUE TITLE
poller_kqueue.inc needs to check return value of `kevent()`

### ISSUE THREAD

**Issue by JackDunaway** [nanomsg/nanomsg#701]
At this line, we're not casing off the return value of `rc`: https://github.com/nanomsg/nanomsg/blob/master/src/aio/poller_kqueue.inc#L109

This was found using static analysis that highlighted an unused but assigned variable.

**Comment by gdamore** [comment]
Just a brief note.  This code is really kind of bogus -- we have no way to cope with an error for the caller.  Really we need to design this code so that it *cannot* fail.  Using condition variables and mutexes instead of relying on frangible system calls would be superior here (for numerous reasons).

**Comment by Crest** [comment]
Deleting a (ident, filter) pair from a kqueue can't fail if the (ident, filter) pair has been registered with the kqueue.

A `kevent(2)` call can't block if the eventlist is NULL. The call can only be interrupted if the eventlist not NULL. Even if `kevent(2)` is interrupted by a signal the changelist ist processed before the signal handler is called.  This can be confusing because most system calls require the exact same arguments to retry the system call after EINTR while `kevent(2)` expects the caller to provide an empty change list to retry only the blocking part after of the `kevent(2)` call was interrupted by a signal.

**Comment by Crest** [comment]
Kqueue supports disabling and (re-)enabling events on a queue without allocating resources (it just toggles a flag in the already allocated structure tracking the event inside the kernel). That way an application can (temporarily) disable an event source without risking failure e.g. if you `accept(2)` an incoming connection on a socket and the protocol requires the server to receive first you register both filters (EVFILT_READ and EVFILT_WRITE) on the new socket but disable the write filter until you have something to send. That way you fail early and there is no need to handle allocation errors in the rest of the API.

**Comment by gdamore** [comment]
That's good information, thanks. 

I'm sort of uninterested in 'fixing' this at present, since I'm looking at other ways to eliminate the whole kqueue/poll/select thing, and instead simply use synchronous threading.  Elimination of async I/O will solve many problems, and is an enabler for refactoring nanomsg to eliminate the FSM madness that makes it incredibly difficult to work with (or to extend).

**Comment by gdamore** [comment]
Closing this in favor of the nng rewrite.  There are other points of fragility in nanomsg, but this one doesn't really come up in practice.
