### ISSUE TITLE
nanocat: error while loading shared libraries: libnanomsg.so.5.0.0: cannot open shared object file: No such file or directory

### ISSUE THREAD

**Issue by har07** [nanomsg/nanomsg#737]
I have installed version 0.9 following *the exact steps* as told in [Build it with CMake](https://github.com/nanomsg/nanomsg#build-it-with-cmake) section of the Readme (no improvisation whatsoever was done since this is my first time trying to build and install package from source). Then I try to run `nanocat` command to verify, as a college told me, but then the above mentioned error message appeared in terminal (Ubuntu 14.04).

When running any of terminal commands mentioned in the build instruction, is there any additional parameter need to be passed or parameter that required to be adjusted to my system in order for the installation to work? (target install location or something, no?)

Installing [go-nanomsg](https://github.com/op/go-nanomsg) afterwards also complained about 'libnanomsg.pc not found' (let me know if this more likely to be go-nanomsg incompatibility with the 0.9 version of nanomsg, in which case I'll try to report in their repo) :

    $ go get github.com/op/go-nanomsg
    # pkg-config --cflags libnanomsg
    Package libnanomsg was not found in the pkg-config search path.
    Perhaps you should add the directory containing `libnanomsg.pc'
    to the PKG_CONFIG_PATH environment variable
    No package 'libnanomsg' found
    pkg-config: exit status 1

Regards,
Hanif

**Comment by gdamore** [comment]
We call the config file 'nanomsg.pc' rather than libnanomsg.pc.   Probably go-nanomsg should be updated. 

I'm not sure why the nanomsg program isn't linking.  Possibly this is a Linux ldconfig thing.  I will investigate further -- my development platform is MacOS X and illumos where ldconfig isn't needed.  (I thought CMake would have taken care of this for me, but I may have been mistaken.)

That said, if you're using *go*, I *highly* recommend mangos -- http://github.com/go-mangos/mangos -- over nanomsg.  It's way more functional, written in pure Go, and almost certainly outperforms go-nanomsg.  It's also *wire compatible* with libnanomsg.  So you can still speak to the same programs.  It's also much more idiomatic go.  And if you don't need wire compatibility, or are willing to create a device to gate requests, mangos offers security via TLS or websocket over TLS.  Finally, it *scales* much better.

(Disclosure: I wrote mangos -- but I'm also the "maintainer" of nanomsg, so you can consider the advice to prefer mangos more or less "official" from the nanomsg team. :-)

**Comment by gdamore** [comment]
So you need to run ldconfig to update the linker cache.  CMake doesn't do this.  This really underscores the fact that we need to prepare binary packages (.deb and .rpm) for Linux.  Sometimes I really hate Linux. 

This would be one of those times.

We can also look at using CMake to do this if doing make install with the default prefix -- but this gets sticky, since users changing the prefix are going to have challenges.  (You don't want this to be done for per-user installs.)

**Comment by har07** [comment]
Hi Garrett, Thx for the fast response.. anyway.. the nanomsg 0.9 installer had an error, there are no file glock.c and glock.h in the src/utils/ so i use the 0.8 version which still have those files.. probably need to update the 0.9 installer..

the pkg_config_path i resolve with add the environment variable after the 0.8 installation success.. running like a charm..

Yeah, i will consider to use mangos.. thx a lot!

**Comment by gdamore** [comment]
Thanks for the glock.c & glock.h feedback.

**Comment by gdamore** [comment]
Hmm... with glock.c and glock.h ... that's strange.  I think maybe the Go build is broken or stale here -- perhaps an earlier build of this library with stale configuration or Makefile bits?  Or perhaps the go package doesn't just use our CMake build?

**Comment by Snaipe** [comment]
The go package is probably using the Autotools generator, which [still references glock](https://github.com/nanomsg/nanomsg/blob/ac6b141b00e43a54eb9b9016d9fa6fa5894202dc/Makefile.am#L126)

**Comment by gdamore** [comment]
Ah. Ok. I removed the autotools support form the master branch already.

**Comment by har07** [comment]
Hi Garrett,
I try to do the cmake build as suggested.. run ldconfig still not solve the problem.. i found that the 0.8 build create files in /usr/local/lib and the 0.9 cmake create /usr/local/lib/x86_64-linux-gnu/ so i copy the file from dir x86_64.. to .. and copy & rename the x86.../pkgconfig/nanomsg.pc to ../pkgconfig/libnanomsg.pc..

**Comment by Snaipe** [comment]
Don't leave the default install directory with CMake -- this depends on your platform/distro defaults, and it's better to explicitely specify the install directory yourself: `cmake -DCMAKE_INSTALL_PREFIX=/usr/local ..`.

@gdamore perhaps `-DCMAKE_INSTALL_PREFIX` should be specified by default to `/usr/local` or `/usr` in the installation instructions.

**Comment by gdamore** [comment]
Ah, well, yeah.  We can suggest that.  Really I'd hope folks installing from source know how to use cmake these days.  That said...  it seems sometimes they don't.  I wonder if I should create a "configure" script that parse --prefix= and just calls CMake...

That said, it would be nice to produce binary packages for these distros.  Distro builders should do the needful IMO.
