### ISSUE TITLE
testutil.h is not helpful btw

### ISSUE THREAD

**Issue by reqshark** [nanomsg/nanomsg#757]
`tests/testutil.h` header does a great job of code abstraction where little or nothing's repeated. 

that fancy code makes the tests harder to follow and more useless when you want to reference implementation or paste simple building-block snippets of patterns/socket types

**Comment by gdamore** [comment]
the idea there is to make it easy to write test programs.  lt isnt meant so much for folks who want to use as a coding example.

**Comment by reqshark** [comment]
sure, but tests extend documentation beyond coding example.. they detail your and other author assumptions, intent about the API and how it should be used

**Comment by gdamore** [comment]
no.  they often delve into internal behaviors and validate assumptions that the core cares about but consumers should not. they often poke at the api in non recommended ways to verify edge case behaviors.  they often intentionally handle errors particularly badly (asserting success instead of testing and handling failures cleanly.)  they may intentionally inject failures to test for internal error handling. 

test cases are test cases.  they are not examples to emulate in real world programs.

**Comment by reqshark** [comment]
ok thanks for the explanation, that makes sense

**Comment by gdamore** [comment]
I'm going to create some demos specifically to help you out here. :-)

**Comment by gdamore** [comment]
Pushed.  Look in git master, under demo/

**Comment by reqshark** [comment]
@gdamore this is great! wow, cool msg control headers. Thank you! 

:)
