### ISSUE TITLE
Missing NN_HAVE_WINDOWS check in poller.h?

### ISSUE THREAD

**Issue by Cthutu** [nanomsg/nanomsg#767]
I don't use CMake to build nanomsg, but rather dropped it inside my project.  I dislike working with CMake  and try not to use it for my projects.  This has worked fine for me on Windows by defining NN_HAVE_WINDOWS, NN_NO_EXPORTS and NN_USE_LITERAL_IFADDR.  I've recently updated the source code and it won't compile poller.h.  I've looked at a diff and the NN_HAVE_WINDOWS check was removed forcing the #error to be compiled since Windows does not have the epoll, poll or kqueue header files.

What am I missing to compile the latest nanomsg code?  I've defined NN_HAVE_WINSOCK but that didn't seem to do any good either.

**Comment by gdamore** [comment]
Building without CMake is *NOT* supported.  A lot of changes have happened recently, and the CMake dependencies have changed.  In this particular case, the pollers are no longer used for Windows; instead we use a simpler solution based on completion ports natively in the worker_win.inc file.

I'm going to close this, because you are well outside of the supported methods for building libnanomsg by not using cmake.

(That said, why do you dislike cmake?)

**Comment by Cthutu** [comment]
It's super complicated, hard to maintain and doesn't work well with non-cmake projects.  It's also a confusing build system to use.  We use premake for our projects.  I am considering removing nanomsg and replacing it with boost::asio just purely because I can integrate the source code into our build environment more easily.

The reason I updated in the first place because the version I was using had a bug where nn_recv returned EAGAIN in blocking mode (contradicting the documentation) and not ETIMEDOUT.  I was hoping the latest might have fixed that but now I can't even compile it.

**Comment by reqshark** [comment]
yea i wouldn't even try to add `poller.c` to the list of files for compiling on windows

**Comment by Cthutu** [comment]
Yes, thank you.  I realised this eventually.  It would be nice if
platform-specific files were in different directories (e.g. posix, windows).
