### ISSUE TITLE
How to used multi thread ?

### ISSUE THREAD

**Issue by sangli00** [nanomsg/nanomsg#780]
sometimes,nanomsg send msg is so much,I used nn_recv can't take over ,msg is lost .
Maybe I create multi thread nn_recv is OK. 
I don't how to create .

**Comment by Snaipe** [comment]
I don't fully understand your problem, but if this is about the fact that nanomsg may lose messages rather than you asking how to multithread some code, then it's likely that you're using a protocol other than REQREP. **All** protocols except for REQREP does not guarantee delivery of the underlying message.

**Comment by sangli00** [comment]
I mean,nanomsg buffer can't take over all nn_send msg. if i send so much msg ,nn_recv can't first time dispose  this msg, I again send msg is error. but now, I think use multi thread dispose msg, `nn_recv` fast  clean buff and dispose msg.

**Comment by gdamore** [comment]
I recommend looking in the demo/ directory of the source tree.  There is a program called "pthread_demo" that shows how to use this.  To use asynchronous calls you need to use the raw mode sockets, because the simpler REQ/REP send/recv code path need to be processed synchronously.

At any rate, this "issue" isn't a bug at all, so I'm going to close it.

Please ask for help on the nanomsg mailing list (nanomsg@freelists.org) if you need further assistance.  Be prepared to describe exactly what problem you are trying to solve, and hopefully we can offer more concrete assistance.
