### ISSUE TITLE
Receiving up published messages

### ISSUE THREAD

**Issue by BillMcCroskey** [nanomsg/nanomsg#797]
This seems to be affecting both C and Go code.
The sender on the Pub side uses a scatter array from the C library with nn_sendmsg.
The sub side was receiving using nn_recv.  The data comes in, but there seems to be a constant memory leak when receiving packets.  I was trying to convert over to nn_recvmsg, but I'm having a bit of trouble trying to setup to pull all data including hdr.msg_control data to make sure I clear the buffers.  Opendns is blocking nanomsg.org, so I'm having a hard time with this at work.   I can get data off the packets with nn_recvmsg, but I still leak memory and that is where I was trying to pull control data as well.
In all cases, the receiver is making sure to empty the receive queue, but leaks still occur.

**Comment by BillMcCroskey** [comment]
Typo - I meant Receiving OF published messages

**Comment by gdamore** [comment]
This seems like a bug.  Can you provide a minimal implementation that
reproduces this behavior?

**Comment by gdamore** [comment]
I wonder why OpenDNS is blocking nanomsg.org though?? That sounds tragic!

**Comment by BillMcCroskey** [comment]
I got it unblocked.

ARM Cortex-A8 CPU.

I might have a small app to duplicate it, but the basic setup is the sender runs a scatter array with two elements:
First element is a structure with two fields

1.       40 char string that holds the packet topic

2.       Uint32_t count of next field
The other scatter array has the serialized string data.
That goes in a nn_sendmsg sent on a Pub socket

Try to receive on a Sub socket with nn_recv.  The packet receives, but use htop and watch the task receiving and it will show memory leakage on resident memory.  Valgrind will also show the nanomsg library as leaking.  It is a per packet leak.

I suspected the nn_recv was not pulling all the content out of the buffer.

I coded up a receive with nn_recvmsg and got it working with stack allocated buffers for the iov[0] and [1].  It ran with no leaks.
Next up, I was trying to get it to allocate on the nn_recvmsg and was trying to get out of segment faults.  I must not have the structures set up right to get it to allocate.
It’s hard to guess the max packet, so I’d like to use the allocator part.  It seems that I should get one element allocated and it should parse out kind of like the data from the nn_recv when I pull it out of the hdr structure.

If I can get the nn_recvmsg call going, I think I have it working.

**Comment by BillMcCroskey** [comment]
Also note that the GoLang Mangos routines used in a similar fashion produce the same leak per packet.

That is nn_sendmsg with scatter array on the Pub and nn_recv on the Sub.

**Comment by gdamore** [comment]
mangos leaks????? that seems hardly possible as there is garbage collection to avoid that in golang.

**Comment by gdamore** [comment]
i need your code to diagnose properly.  which transport is this?

**Comment by BillMcCroskey** [comment]
Ipc to a file point in /tmp.

Pub on one end, Sub on the other.  Send with nn_sendmsg on Pub, receive with nn_recv on Sub.

I’d have to set up a small project as my small program has too much internal content.

**Comment by BillMcCroskey** [comment]
Found the issue, you can close the topic.

The buffer being filled was a char * and not a void *.  The change fixed the leak.

**Comment by gdamore** [comment]
so not a nanomsg bug then?

**Comment by BillMcCroskey** [comment]
No

**Comment by BillMcCroskey** [comment]
False hope, it sill leaks

**Comment by BillMcCroskey** [comment]
We are on an old version of nanomsg and will upgrade to latest and repeat test.
The main thing I need to get working is nn_recvmsg with nonomsg allocating the buffer.  Following the guild, I can’t get it to work.
We will try it first on a newer version.

**Comment by gdamore** [comment]
that should work fine.  you do have to free the message yourself though once you are done with it. 

try writing the smallest program you can that  reproduces the problem. 

note that there is no difference on the wire if you use gather to send a message from different chunks so that should not have any effect on the receive side.

**Comment by BillMcCroskey** [comment]
I  got it working.  I got the nn_recvmsg working, but the root of the problem was not passing a pointer to a void * on the receive in that case.
No leaks on the ‘C’ side.  I’ll have to look at the GoLang side.  It is possible to leak faster than the garbage collection – seen in two applications.

Thanks!

**Comment by BillMcCroskey** [comment]
Further checks still show a leak… I’ll setup a small program to run it down or try V1.0

**Comment by BillMcCroskey** [comment]
Working on getting V1.0.0 working, but found what is going on with 0.4beta:
On a sub side of a socket, any program leaks memory when there is more than one topic running on the bus and your subscription covers only one of the topics on the bus.
That was why it worked sometimes and would break at times.
Nanocat leaks the same under that condition. Macat leaks all the time.

**Comment by gdamore** [comment]
Ah, *that* is useful information.  I can try to confirm this, and if so, a
fix should be straight-forward.

nanocat and macat are really test programs — its unsurprising that they
leak in variety of situations; I wouldn’t use them in long-running
situations.  That said, we should find and fix any leaks that may exist.

**Comment by BillMcCroskey** [comment]
Yes, I just use them for test, but I was trying to see if I could get a different code base to produce the same result in the same situation.

GoLang routines build from mangos leak in the same pattern of subscribe to one topic when two are on the bus.

**Comment by gdamore** [comment]
How did you assess the leak in mangos?  In particular, I see this in the subscriber code for mangos:

                if !matched {
                        m.Free()
                        continue
                }

It looks like it makes a reasonable effort to *not* leak.  I will check nanomsg next.

**Comment by gdamore** [comment]
And I see almost exactly the same logic in nanomsg xsub.c:

        rc = nn_trie_match (&xsub->trie, nn_chunkref_data (&msg->body),
            nn_chunkref_size (&msg->body));
        if (rc == 0) {
            nn_msg_term (msg);
            continue;
        }

I want to know how you demonstrated the leak?  I am going to try to reproduce myself with nanocat (and perhaps macat).

**Comment by gdamore** [comment]
So, I can't see a leak using nanocat.  I'm using a single subscriber with about 200 publishers, but I'm subscribing to messages from only about 11 of them.  They each publish a message at one second intervals.  This is using the TCP transport on MacOS X.

Note that I *do* see a fixed size increase per socket (not per message) that I've connected.  That's normal and expected behavior as there are data structures per connected TCP stream.

Its possible that a single message is "leaked", but its definitely not continuous.  (I'm not verifying with vgrind or anything like that, just watching the process looking for increasing heap growth.  I'm not seeing any of that.)  I would be *far* less concerned about leaking a small amount of resources just a single time (e.g. a buffer leak at start up), provided that memory consumption does not grow over time/usage.

If you can write a shell script that demonstrates the leak, and describe how you are verifying that such a leak exists, it would be useful.

**Comment by BillMcCroskey** [comment]
nanocat --sub --connect-ipc /tmp/Pub_bus.ipc  -A --subscribe My.Data.One

Send from the pub side two topics.  My packets are 40-byte topic region (set to length 40 in socketopt), 4-byte length of the data field, the data field of serialized data (variable length).

From valgrind:
==4118== 32,268 bytes in 213 blocks are definitely lost in loss record 34 of 34
==4118==    at 0x4833CC0: malloc (vg_replace_malloc.c:291)
==4118==    by 0x4880307: nn_chunk_alloc (in /usr/lib/libnanomsg.so.0.2.0)

**Comment by BillMcCroskey** [comment]
Unless you use the –i 1 on nanocat, you can’t get it to stay on the bus and send.  I’m having a hard time getting a shell script to do what the program does.
The leak is continuous and per packet.  Watching the “RES” field in htop will show what valgrind is reporting.

I’d have to make up a small program.

**Comment by gdamore** [comment]
I will have to download valgrind to test… I did use the -i flag to nanocat.

I wonder if the problem is that packets are getting lost when you
disconnect?  That actually makes more sense to me as a potential area of
concern.

**Comment by BillMcCroskey** [comment]
The loss is on maintained connections that never drop the channel.

I have some small packet encoders that generate messages.  On those, I had to connect, delay at least 50mS, send, delay at least 50mS, then disconnect to get data on for testing packet based handling.  If you don’t do that, not all subscribers get the data, I think this is why you need the –I on nanocat – must be link control under the hood.

The loss showed up once I got two subscription topics running on the bus on the maintained links.
A request goes to the server on a pipeline, then the data is streamed to the clients on a sub bus.  Two clients hit a server for their request.  Each client is looking for its subscription for the data.
I’ve not looked at the nanomsg code, but my mental model is that the subscription is a filter before the receive – each client should never even see the other packets from the other subscription, yet it seems there is impact.

**Comment by gdamore** [comment]
Your mental model is close to the right semantic, but absolutely wrong in terms of what happens under the hood.

Under the hood, every client subscriber receives every message (provided enough queue room exists), but the ones they aren't interested in are discarded (see the snippet from above in xsub.c) -- basically we do *client* side filtering rather than server side.  (There are some really really strong reasons why we do it this way, and that's not going to change anytime soon.)

A 50 ms delay after connect is typical -- this is because it takes time for all the setup in the underlying plumbing to be complete -- though it sounds excessive for IPC.  (For TCP its typical.)

I'm astonished you're seeing lots of leaked messages -- what version are you using?  I've not been able to see that even while sending several hundred messages per second (both with discard of 90%, and no discarding) -- but this was with nanocat.

If you're allocating your own messages, you do need to be careful to make sure that you're not holding an extra reference to the message in your application.  The best way to do this IMO is to use NN_MSG to ask for the framework to provide you with the message, which than can be tossed with nn_msg_term() once you are done with it.

**Comment by BillMcCroskey** [comment]
Running 0.4beta right now, trying to get the build of v1.0.0 working (another developer).
The actual running processes don’t do the wait, just the command line test encoders (for software unit test).

For all receives, I pass a pointer to a void ptr and size NN_MSG for it to allocate and then call the nn_freemsg to release the buffer.  Nothing is held from the buffer.
I’m using various sockets such as NN_Bus, NN_Pipe, NN_Sub.  NN_Sub is the only case of this problem.  Nothing else leaks.
Perhaps this issue is fixed in V1.0.0?

Yes, I expect the filtering to be client side.  The question is, if every packet comes to the client, do I need a way to deallocate the ones that did not go through the subscription?  I am in the non-blocking mode, I read the socket down to empty to get a -1 on count.  The other topics don’t come though the filter with subscription, so other than at your layer, how would one delete them?

**Comment by gdamore** [comment]
There was a known leak affecting xsub, which was fixed nearly two years ago: d265c745977b273fcb219c529a3b6874e8ae1d67

This leak *did* exist in 0.4.  So yes, you need to update.  Until you do that, I'm not going to spend more time on this.  (0.4 was released in January of 2014!!)

That said, you obviously have no way to handle messages you don't receive, nor are you expected to.  The library should take care of them for you.  If there is indeed a verifiable leak happening in new code, that would be a bug.  I've not been able to see such behavior.

**Comment by BillMcCroskey** [comment]
OK, we will get V1.0.0 running.  Our build of it ran into an issue during the nn_bind on a connection (I’d have to look-up what protocol it was on).
At least it sounds like a root cause has been located, so I’ll quit debugging my code and get the update running.
I was trying to get some features/functions running when I ran into this, so I’ll retest when we get on V1.0.0 and let you know.
