### ISSUE TITLE
accept4 not implemented on all systems

### ISSUE THREAD

**Issue by mrhubbs** [nanomsg/nanomsg#800]
nn_usock_accept fails on some POSIX systems, aborting the application with errno set to 38 (not implemented).

Some research reveals that accept4 seems to be stubbed out on some POSIX systems, but not actually implemented.  Thus the configuration may set NN_HAVE_ACCEPT4 to "yes," even though the system doesn't actually implement it.

Perhaps the code in nn_usock_accept (usock_posix.inc) should be extended to automatically fall back on accept if accept4 fails?

**Comment by gdamore** [comment]
interesting idea.  

which system was this on?

**Comment by mrhubbs** [comment]
An arm 7, using GNU C tools.

**Comment by gdamore** [comment]
But what operating system?

**Comment by mrhubbs** [comment]
I'm sorry, can't see the forest for the trees.  Linux. Kernel version 2.6.  It's an embedded system.

**Comment by gdamore** [comment]
it is bizarre that accept4 doesnt work on this system.

**Comment by mrhubbs** [comment]
Yes. I would not have expected that. I verified that errno was set to not implemented after the accept4 call.  Googling "accept4 not implemented" returns a number of hits. Here is one: http://lists.busybox.net/pipermail/uclibc-cvs/2011-September/029878.html

The system I'm working on uses busybox. I'm not sure if that makes a difference.

**Comment by dangerousHobo** [comment]
Support for the `accept4` syscall for ARM was added in 2.6.36. [syscalls(2)](http://man7.org/linux/man-pages/man2/syscalls.2.html) reports support existing in 2.6.28 but this was apparently initial support. glibc version 2.10 or newer is required (not sure about musl or ulibc). The `accept4` syscall didn't exist in FreeBSD till 10.0.

**Comment by Crest** [comment]
Nanomsg doesn't have to worry about FreeBSD < 10.0 because FreeBSD 9.3 is the only still supported FreeBSD release without accept4() and it will reach EoL status by the end of this year. It would be nice of nanomsg to compile (and work) on FreeBSD 9.3 until than because it simplifies my life as port maintainer.

**Comment by gdamore** [comment]
@Crest but if you don't have accept4, and your OS doesn't *claim* to have it (i.e. it doesn't exist in header files) you won't have a problem.

The problem we have is that we have one system that has accept4 defined/declared, but its non-functional (just returns ENOTSUP).  This is Linux lunacy.

**Comment by Crest** [comment]
FreeBSD doesn't claim to have accept4() unless it has a working accept4().

**Comment by gdamore** [comment]
I think a similar problem can occur with pipe2.  The issue is that we have versions of glibc that are delivered separately from the kernel; if a new glibc is run with an older kernel, the glibc function will exist, but the underlying system call in the kernel won't.  This is a bizarreness that comes about because in Linux-land the kernel and C runtime are independently delivered.  (It can also happen e.g. with uLibc or other libc replacements.)
