### ISSUE TITLE
Suggestion: search for documentation

### ISSUE THREAD

**Issue by kroggen** [nanomsg/nanomsg#820]
When we search on google for some nanomsg function it shows the docs for v0.1.

I know this is not the correct way to search the docs, but it is the way most of us do. Just type in the browser and we get the results.

Example: when we search for nn_send the first item on Google is:

http://nanomsg.org/v0.1/nn_send.3.html

What about having a link to the newest version of the pages somewhere there on these pages?

I use nanomsg for more than a year and always using these old docs :(  This may be happening with many other people. A look in the HTTP access logs may reveal if this is happening.

It is just a suggestion.

**Comment by kroggen** [comment]
Although the documentation encourages to use nn_errno() function on the nn_errno page, it does not do the same on other pages. Example:

Even in the nn_strerror page it shows an usage without the nn_errno function.

I guess it could be: `nn_strerror(nn_errno())` instead of `nn_strerror(errno)`

Or am I missing something here?

The same for other pages that use it

**Comment by kroggen** [comment]
This is giving 404:

http://nanomsg.org/v1.0.0/nn_term.3.html

**Comment by kroggen** [comment]
Guys, I need to share this with you.

I am the developer of [litereplica](http://litereplica.io) and it uses nanomsg.

We (I and the litereplica users) were having errors going on and the debug showed that the problem was with nanomsg.

It occurred only with the TCP transport, not with IPC.

At some point the connection was broken and nanomsg did not made the reconnection. I could check it with netstat.

A customer from a company was asking to remove the nanomsg because of this.

Only after dozen of days I realized the problem:

The sender was sending a message with a size of ~1.4MB and the nanomsg has a limit on the received message size (I did not know about this).

I almost gave up and let nanomsg aside.

So here is my questions: should it have this limit as the default? If yes, what about having something wrote about this in the nn_send documentation page?

**Comment by gdamore** [comment]
Yes this limit is intentional. It is set to 1MB bu default.  You can remove the limit if you like.  The reason for the limit is to protect against a trivial denial of service attack - a sender could claim to send 1 GB for example, and the receiver has to allocate heap to receive this even if the sender doesn't actually send any data.  The 1MB default limit was chosen as a compromise between safety (4000 senders would be needed to cause a 4GB heap allocation) and usability.  We felt that few people use nanomsg to send messages larger than this.  Those that do so, should only do so on networks that they trust and can increase the limit or remove it altogether. 

This is documented in the nn_setsockopt page.  We should probably mention the existence of a limit in nn_send and nn_recv as well. 

In fact I really do not recommend nanomsg as a transport for very large messages.  If any data is lost then the entire message will need to be resent.  Additionally nanomsg tends to be optimized for lots of small messages rather than straight throughput. 

If you want maximum raw throughput using the underlying transport (TCP) directly is likely to be superior.

**Comment by kroggen** [comment]
Thank you for the clarification!

**Comment by gdamore** [comment]
I've fixed the documentation and now we correctly link from old pages to the latest.  I am closing this issue now.
