### ISSUE TITLE
Question on nn_poll and CPU usage

### ISSUE THREAD

**Issue by edufschmidt** [nanomsg/nanomsg#829]
Hi there, 
we have been using nanomsg in our project for a while now, mainly as a communication infrastructure for a multi-process application. We have several (~20) publishers and a few subscribers, among which there is a "gateway" node responsible for concentrating data gathered from different parts of our system and packing it in a different format for the purpose of updating a web GUI.
We are using nn_poll for receiving messages in all nodes, which allows for the monitoring of more than  one socket, but noticed that the "gateway" node's CPU usage is much higher than the other node's when running on our target platform (Beaglebone Black, ARMv7, embedded Linux). When running on a mid-end PC, the problem becomes negligible.
Of course, this must be happening because the traffic to this specific node is much higher than to the others, but we are wondering whether there is a more efficient way, in terms of CPU usage, to receive the messages.
Thanks in advance!

**Comment by gdamore** [comment]
At this time, not really.  You could possibly eliminate the use of nn_poll() and go to normal blocking synchronous operations (but only if your design allows for this), but I'm not sure that it will save all that much.

In the future a new design will reduce the overhead somewhat, as well as the latency, by making better use of condition variables instead of the magical file descriptor based approach that nn_poll() uses under the hood.

**Comment by edufschmidt** [comment]
Thanks for the quick reply! We are looking forward to this new design, and are eager to help on any specific task you have on this direction. Meanwhile, I guess we'll stick with our implementation using nn_poll, which is available in the [Tangle](https://github.com/edufschmidt/tangle) repo in case you wanna take a peek at it.
