### ISSUE TITLE
nanomsg on embedded realtime systems?

### ISSUE THREAD

**Issue by peters-r** [nanomsg/nanomsg#855]
Hi,
is there any experience with porting nanomsg to an rtos (e.g. FreeRTOS) ?
What are the dependencies?
How much ROM / RAM does the library consume?
Would it fit into an ARM Cortex Microcontroller?

Thank you in advance,
Richard

**Comment by gdamore** [comment]
I know that some work was done to port nanomsg to QNX, and it largely just
worked (modulo some weirdness with IPC based URLs.)

Nanomsg was designed with this use case in mind, and so it *should* work.
That said, nanomsg does depend on having some things that your OS may or
may not provide; and you may have to do some work to provide the underlying
functionality:

a) Mutexes
b) Condition variables
c) Threads (nanomsg only uses a few threads btw)
d) POSIX compliant I/O (with select or poll at least) — or some other async
I/O scheme (you’ll have to write code if isn’t POSIX)

From glancing, it appears that FreeRTOS isn’t going to work out of the box,
mostly because it doesn’t support either POSIX or Win32 APIs natively.
This might be an interesting project for someone to undertake.  There
apparently is a way to emulate FreeRTOS on a POSiX system, which might make
the work of porting nanomsg to FreeRTOS easier.

**Comment by gdamore** [comment]
This is a question, not a bug or change request.
