### ISSUE TITLE
Clarify windows build steps

### ISSUE THREAD

**Issue by martinlindhe** [nanomsg/nanomsg#859]
Took me a while to figure this out, and I feel it could be mentioned somewhere in the README perhaps, since it differs quite a bit from how cmake is normally used on Linux/macOS.

To build release x64 binaries on Windows, using Visual Studio 2015 (from cmake), one needs to do the following

    mkdir build
    cd build
    cmake -G "Visual Studio 14 Win64" ..        # version 14 is mapped to Visual Studio 2015...
    cmake --build . --config Release            # -DCMAKE_BUILD_TYPE=Release has no effect all here

**Comment by gdamore** [comment]
Actually, the generators used for CMake depend greatly on the contents of the environment.  I use the nmake based generators and that way I can just do NMake most of the time.

**Comment by martinlindhe** [comment]
Okay, a documented usage of nmake would also be of interest.

**Comment by gdamore** [comment]
You would use -G "NMake Makefiles".

Normally CMake tries to choose a reasonable default generator.  It doesn't always choose well.  I would hope that Windows developers are familiar with the problems associated with this on Windows.

Btw, Visual Studio Code has CMake support "built-in", so that pretty much Just Works.
