### ISSUE TITLE
Support Secure Web Sockets

### ISSUE THREAD

**Issue by briankwest** [nanomsg/nanomsg#862]
I can't find any documentation that outlines how to use this library securely, Was this something that will be on the roadmap anytime soon?

Thanks,
/b

**Comment by gdamore** [comment]
Today, libnanomsg does not have any kind of security built in, but you can "fake it" by using a device along with mangos (github.com/go-mangos/mangos), which *does* support both TLS and secure websockets.    What you do is have a mangos device that proxies from TLS (or WSS) on one end, and forwards to a local libnanomsg client over a secure local transport, either loopback TCP or UNIX domain sockets.  (Of course if you are writing in golang, you don't need to use this proxy at all, just use mangos and go on happily without nanomsg. :-)

 Adding encryption to libnanomsg itself has proven to be sufficiently challenging that nobody has done it -- mostly because if the byzantine state machines internally used.

I'm in the midst of a major redesign (wire protocol compatible, just like mangos) that definitely has aspirations to support TLS, secure websocket, and probably also an SSH-based transport.  (I'll probably add SSH transport to mangos too).  This design is based on experience gained implementing mangos.  You can see my work in progress at github.com/nanomsg/nng -- the roadmap is that at some point nng will replace libnanomsg.  However nng is in its infancy, and so is not ready to do this.   However, it *is* functional enough to start experimenting with.  (The timeline for more serious beta testing and pre-deployment is probably still a couple of weeks away, especially for folks that want to use the libnanomsg API compatible shim.)

Note that all three products, nanomsg, nng, and mangos, can all speak to each other over TCP and IPC.

**Comment by gdamore** [comment]
So this will be coming soon nng.  But probably never in nanomsg.

**Comment by gdamore** [comment]
Closing this as 'will-not-fix'.  (again, I *will* be doing this in the follow-on nng library, probably later this month.)
