### ISSUE TITLE
Tests failed when building on WSL

### ISSUE THREAD

**Issue by alexeykuzmin0** [nanomsg/nanomsg#871]
When building nanomsg on Windows Subsystem for Linux, ctest shows the following test errors:
> 86% tests passed, 6 tests failed out of 43
> 
> Total Test time (real) = 145.57 sec
> 
> The following tests FAILED:
>           3 - ipc (OTHER_FAULT)
>           4 - ipc_shutdown (OTHER_FAULT)
>           5 - ipc_stress (OTHER_FAULT)
>           7 - tcp_shutdown (Timeout)
>           8 - ws (Timeout)
>          35 - separation (OTHER_FAULT)
> Errors while running CTest

**Steps to reproduce:**
1. Use a computer with Windows 10 with Windows Subsystem for Linux component installed.
2. Launch bash.
3. Download and unpack nanomsg-1.0.0 or checkout code from master.
4. Go to the root directory of the sources.
5. `mkdir build`.
6. `cd build`.
7. `cmake ..`.
8. `cmake --build ..`.
9. `ctest -C Debug .`

**Expected behavior:**
ctest shows no failed tests.
**Actual behavior:**
ctest shows failed tests.

**Comment by gdamore** [comment]
I haven't looked at any of this.  I'm not surprised that the IPC tests fail hard -- it's likely that UNIX domain sockets are simply not supported on WSL -- the underlying system doesn't have anything like them; Windows Named Pipes are quite a lot different.

The other tests will take more time to debug.   WSL is effectively a new (and right now unsupported) platform for nanomsg.

**Comment by gdamore** [comment]
So tcp_shutdown and ws are the only tests that are *not* failing to IPC.  (separation is in fact using IPC.)

**Comment by gdamore** [comment]
I'm probably not going to bother to fix these in nanomsg.  For nng we will look at it.

**Comment by gdamore** [comment]
So I tested with the very latest WSL today.

Most things work... but .. IPC is totally absent -- (you get EPERM if you try to open an IPC socket), and TCP works "funny" in that SO_REUSEADDR does not have the normal semantic ... instead it lets any process bind to the same port.  And, frankly, you want SO_EXCLUSIVEADDR, but I have no idea how to get that from the WSL subsystem.

I will try to add code to detect WSL, and disable SO_REUSEADDR in that case.

**Comment by gdamore** [comment]
I really can't do anything about IPC... since I have no idea how to get to Named Pipes from WSL.

**Comment by gdamore** [comment]
Good news... I have local code that fixes these -- basically the IPC related stuff is disabled, and the TCP test is working.   The tcp_shutdown test fails because for some reason setting up 100 threads doing bind / connect takes too long, and it times out.  I've reduced the count to 10 threads for WSL only, and then it passes.  I had to bump the timeouts up from 5 seconds for the ws and tcp tests as well, because again Windows seems to take longer to set up and tear down connections, and WSL is even slower than the host Windows.

I would *not* attempt to use WSL for anything production wise based on my tests.  It is interesting, and having nanomsg work there is a pretty nifty idea.

Btw, we detect WSL by noticing Microsoft in the uname version.
