### ISSUE TITLE
(Question) Which, if any, transport/protocol actually uses shared memory ?

### ISSUE THREAD

**Issue by JPGygax68** [nanomsg/nanomsg#902]
I have a use case where I need to transfer encoded video packets between processes. I had my own implementation based on shared memory (via boost interprocess), which however proved too unstable, and motivated me to give nanomsg a try.  (Btw: congrats on a simple and clear design!)

My only (slight) worry is that I may be introducing extra latency, since I'm implementing a screen sharing application. Hence the question: how do I minimize latency / can I get nanomsg to do zero-copy interprocess communication ?

**Comment by gdamore** [comment]
nanomsg does not today implement any kind of shared memory transport.  There were designs intended to make this possible via the IPC, but we've just never gotten around to it (and shared memory turns out to be really hard to do right in a general purpose networking stack because you have to manage resources allocation and deallocation properly -- the latter being fairly hard to get right in a non-racy manner.)

A good question, however, is whether you really need shared memory transports.  The loopback TCP is surprisingly fast, and IPC is available as well; modern CPUs copy data actually pretty darned quickly.

If you assume *zero* compression, and want to encode 4K video streams (24-bit color) at 60Hz, you need something like 17Gb/s.  A naive run using 256K message sizes over TCP on my laptop macbook pro gets about 18 Gb/s.  Larger message sizes have better perf...   using 2MB messages I get about 20 Gb/s.  Using UNIX domain sockets I get about 30 Gb/s.  These are single threaded numbers (1 thread sending, one thread receiving) -- reproduce the results from using the local_thr and remote_thr utilities btw.

That's for throughput, and it indicates the sustained performance you have to provide to be jitter free.  Of course, there is also latency, but the latency you will get over this kind of session is so small as to be unnoticeable by humans.  (Typically we don't notice audio latencies until they reach up to about 30-40 ms.  I'm not sure what the video tolerances are, but I suspect that they are similar, or even more tolerant.  For example, most gaming platforms can tolerate latencies of more than 50-60 ms before even the best players notice.

In the future, we may provide a true zero copy transport for nng (the successor to nanomsg, but having a compatible API) -- there are use cases like yours, and others (high speed storage) which would benefit from reduced data copies and higher throughput.

**Comment by JPGygax68** [comment]
Thank you, Garret, for this detailed and very helpful answer!

The situation is therefore as I suspected; I indeed discovered for myself
that implementing such a thing was less fun that I thought it would be, and
the end result turned out not to be very reliable in the end, even with all
the effort I spent.

I do think however that it could be done based on your design (I didn't
know a successor was in the works already).

I really appreciate your insights and calculations about bandwidth,
latency, and jitter, as those are indeed the things I'm concerned about. I
suspect I do not absolutely need zero-copy, and that the gain in stability
will more than make up for any lost microseconds. The biggest contributor
to latency will still be TCP over the LAN (yes TCP - I was surprised that
the increase in latency was negligible, especially considering there was no
other easy way to compensate for lost packets).

I also agree that zero copy remains of interest though. As a bit of
background, my use case is actually a case of a 32-bit (Windows)
application that is exhausting its address space while being too big and
complex (and heterogeneous: Fortran and C++) to just easily switch over to
64-bit. I decided to try and use a "satellite process" to offload the work
of muxing and sending the video stream over the network (using the FFmpeg
library). The implementation seems shaky, but works in principle; and I do
believe there is more potential to this satellite process idea: done right,
it could serve as the basis for complex interactions between large and
heterogeneous software components, each of which would benefit from full
protection by the OS (a bit like browsers protect individual tabs, come to
think of it).

Thanks again, and best wishes!

**Comment by gdamore** [comment]
Btw, the architecture of "satellite" process leads towards a current popular design pattern -- "microservices architecture".  This is a good solution to breaking up a complex system, with many benefits.  nanomsg is designed to act as the fabric/glue/transport for such systems.

**Comment by JPGygax68** [comment]
I wasn't familiar with the term - thanks for that.
