### ISSUE TITLE
(Question) How to prevent having multiple servers binding to a pipe

### ISSUE THREAD

**Issue by JPGygax68** [nanomsg/nanomsg#903]
Is there a way to reliably avoid having multiple servers binding to the same ipc pipe ?

I tried this just now on Windows with NN_PAIR, and the behavior is this:
- both servers bind to the same socket (pipe) without reporting an error
- the second server, having bound after the connection from client to server was established, does not get any messages
- once both the first server and the first client have terminated, a second client now connects to the second server and can send messages

(I haven't tested any extra variations.)

My use case is still the same, a satellite process. It would be nice to have a way to reliably avoid having multiple instances of that satellite (server) process. However, if you see now way to ensure that, my fallback would be to simply let it run and timeout after a period of inactivity.

**Comment by gdamore** [comment]
nng actually solves this.  With nanomsg, the problem is that while only one server is actually bound, you don't get any feedback that the other server failed to bind -- it just sits in the background and keeps trying.

nng isn't quite ready for production yet, but you can try it for this.  It is wire protocol with nanomsg (although for NN_PAIR you have to ask for the older pair protocol -- we have a newer one in nng that is used by default.)

**Comment by JPGygax68** [comment]
Thanks again, I may give this a try!
