### ISSUE TITLE
Client wakes up every 100ms in the pubsub demo

### ISSUE THREAD

**Issue by fuine** [nanomsg/nanomsg#922]
To reproduce run a server and a client as described in the instruction of `demo/pubsub_demo.c`. Next spawn another client but prepend the command with `strace`. You should see a lot of `poll([{fd=5, events=POLLIN}], 1, 100) = 0 (Timeout)` messages.

Client should not create so many `poll()` events, but rather it should properly block until the real message arrives.

CC @gdamore

**Comment by gdamore** [comment]
I've spent a bunch of time trying to fix this, the problem is close() doesn't wake things up, and we can wind up having sockets stuck in poll() when we close.

I've tried switching to a condvar / mutex scheme as well, but I'm having trouble with some deadlock conditions in that case as well; I think the problem is that this interacts poorly with the state machines and contexts associated therein.  Simple retrofits of a new strategy don't work well.

I may wind up implementing a global poller that wakes *all* sockets when socket conditions change.  This may be the only way to properly cope with this.

**Comment by gdamore** [comment]
Sorry, I mean wakes "all sockets" when any socket is closed.

**Comment by gdamore** [comment]
Good news... I found a simpler fix.

We just needed to defer the close of the event file descriptors until all outstanding user operations have completed, and fortunately we already had a hold/release mechanism to give that to us. 

I was also able to simplify the poll() logic quite a bit.

**Comment by fuine** [comment]
@gdamore Thanks for a quick fix - great work :)
