### ISSUE TITLE
nn_recv got messy code

### ISSUE THREAD

**Issue by DyncKevin** [nanomsg/nanomsg#927]
in my project, i use req/rep and pub/sub
and i use code "nn_recv(nn_sock_req_, &msg, NN_MSG, 0)" like this to recv data,
but i found when i print msg out, it will be messy code sometimes, like this " "SysMsg":[]}}Q\261 "

"Q\261" is messy code.
at first it appear occasionally, after i check my code i found i forget add nn_freemsg.

**but after** i add nn_freemsg, this issue appear every time.

who can tell me, what's my problem.

the following is the main code about nn_sock_req_
nn_sock_req_ = nn_socket(AF_SP, NN_REQ)
nn_send(nn_sock_req_, strContent, nContentLen, 0);
int rc = nn_recv(nn_sock_req_, &msg, NN_MSG, 0);

**Comment by SG7** [comment]
Just make sure that you terminate a string on send.

This
nn_send(nn_sock_req_, strContent, nContentLen, 0);
may rather look like:
nn_send(nn_sock_req_, strContent, nContentLen+1, 0);

**Comment by DyncKevin** [comment]
@SG7  thank you for your quick reply.
i know a string need to be ended by '\0'
but the server side is running with NodeJS, the msg nn_recv is not from my 'nn_send', but from nodejs server.
and i print out char code on nodejs side, there is no messy code in the end.
when nn_recv, how i know the server reply with '\0'

as the following log shows

(MsgSyncer.cpp:79): ++++++++++++++MsgSyncer::DoRepReq LOG msg strlen is:531, msg:{......"Content":"刚才吃不饱","S**_eqn":135_**,"STime":1509672393389}}],"GroupMsg":[],"FcMsg":[],"SysMsg":[]}}

(MsgSyncer.cpp:79): ++++++++++++++MsgSyncer::DoRepReq LOG msg strlen is:311, msg:{......,"SysMsg":[]}}**_eqn":135_**,Ѹ

these are two nn_recv logs from same file, "MsgSyncer.cpp:79", the first log is a right and normal log, but the second, notice, at the end, appear "eqn":135" which had appear in the first log

what should i do ? thanks

**Comment by gdamore** [comment]
So the problem is that the node code is probably *not* terminating the strings with a zero byte.  That's perfectly reasonable.  Many languages do not treat \0 specially, and frankly its better that they don't.

You need to look at the received packet, *and* the length.  E.g. if the packet received contained 'H', 'E', 'L', 'L', 'O' and was 5 bytes long, then the receive buffer might contain any random byte at the sixth position.  (It is statistically likely that this will be zero pretty often, but that's an accident of fate, rather than a design.  The bytes after the last byte of the message are "undefined", and can be any value.

This is a common point of confusion; you can solve this by allocating a scratch area (if you need), and then copying "length" received bytes into it, and then adding the \0 at the end afterwards.

If you control the sending side, you can also have it append a \0 into the payload on send.  That may feel awkward though, and I don't normally recommend it.

The better way is simply to limit what you look at to the length that was actually sent.  If you're dealing with JSON payloads for example, the JSON framework might not require the string be NUL terminated -- you might be able to give *it* a length.  For example cJSON has an API called "cJSON_ParseWithOpts() that allows you to indicate whether a NUL byte at the end is required or not.  json-c has one called json_tokener_parse_ex() that lets you specify the length of the incoming buffer.

**Comment by DyncKevin** [comment]
@gdamore thank you for your reply and advise
because i used node-nanomsg on nodejs side, so i had thougth nanomsg had solved this kind of issues. I know it's my problem, i will have a try on cJSON.
thank you very much!

**Comment by DyncKevin** [comment]
@gdamore @SG7 
the issue had solved. it's my problem
i just use the data 'msg' nn_recv and forget the return value msg length
so when i pass msg to another method, i just pass 'msg' without msg length
i did't write c-code for a long time, i forget this.
thank you for yours time again!
