### ISSUE TITLE
nn_term will crash if no nn_socket is ever created

### ISSUE THREAD

**Issue by alenwesker** [nanomsg/nanomsg#935]
It's simple to recreate the scenario, just call nn_term directly with no nn_sock calling will cause the crash; 
I debugged out the reason:
self.lock is not initilized.
self.lock is initilized in nn_lib_init

The situation is rare in my app, that with a dozen of conditions in my multi-thread app accidental satisfied, no agent is created, then the final cleaning that calls nn_term will crash. 

It's easy for me to work around, just add a judgement on the agent number. 

But I think it should be refined, that manomsg is focus on high reliability regardless on the state.

I suggest add a non-initialized state, that nn_term will not crash even no sock was ever created.

**Comment by SG7** [comment]
Well, this is similar issue to https://github.com/nanomsg/nanomsg/issues/890.

**Comment by gdamore** [comment]
I need to think about this somewhat.  The problem with arbitrary non-initialized states is that they need to be protected against concurrent threads access; historically we've taken the view that the lack of a standard way to statically initialize a lock on some platforms was a stopper to handling this sensibly.

In retrospect, modern platforms (Windows Vista and later for example) and POSIX do offer static lock initialization.   Dealing with "other" platforms is not really all that interesting anymore for nanomsg.  So maybe its time to just address this properly.

Having said all that, I view nn_term() as a dangerous API, and I would discourage it's use.  The only realistic use for it is cleanly release resources in an application just before exit(), because you want to avoid false positive from resource leak detectors.  Outside of that one case, there is no other real need to ever call nn_term(), and doing so in a library can be destructive to other library consumers or the application itself.

(Problem here is that we don't have a matching "init" to "term" behavior, so reference counting won't work.  This is a design defect in the original API.)

**Comment by gdamore** [comment]
The only time to call nn_term really is atexit().  Or possibly, if you're unloading the library (and are certain that there are no other library consumers.)

**Comment by gdamore** [comment]
Good news, we have nn_once already.  So the fix is easy.
