### ISSUE TITLE
Windows OneCore and UWP compilation

### ISSUE THREAD

**Issue by devdimager** [nanomsg/nanomsg#941]

**Comment by devdimager** [comment]
Hi, I would like use nanomsg under Windows OneCore. I was not able to load nanomsg.dll, i assume because dependencies. ws2 are supported in OneCore, but not shure regarding advapi32.dll.

**Comment by gdamore** [comment]
So I have no experience with the new Windows OneCore.  I'm pretty sure we do a few things (abort() for one!) that may be problematic on that platform.

I suspect libnng may be closer to what you need there....

**Comment by gdamore** [comment]
I'd need more information here... but I think UWP prefers static linking -- you would need to depend on the same libraries, but I believe they are available for UWP.

Initial attempts to build seem to work reasonably well for NNG at least.  I've not tested nanomsg building.

**Comment by gdamore** [comment]
Can you provide more information about the errors, and how you've built it.  I don't have sufficient information to proceed.

**Comment by gdamore** [comment]
I'm closing this due to lack of feedback.  In any event, if you're using UWP, you really should be using NNG at this point.  I'm really not interested in enabling new platforms for the C API of legacy libnanomsg.  (If you need it on a platform because you need support for a language runtime, such as python or java -- then we should talk more.)
