### ISSUE TITLE
REQ/REP like  protocol with server sending data to clients.

### ISSUE THREAD

**Issue by douglascordeiro** [nanomsg/nanomsg#945]
Hi, I'm having trouble in chossing the right type pattern which I should use.

I need to connect several clients(100 - 10000) to one server.
The server needs to send information to individual clients and those clients should reply(or not) to the server.
I don't find any pattern that do that in the documents.

I could use REQ/REP + PUB/SUB, but PUB/SUB is no use for me as it send information to all connected clients and this generate absurd network bandwidth usage.

Any help?

**Comment by gdamore** [comment]
You could use req in raw mode. Will be hard because you would need to know
which pipe id is associated with which client. Alternatively you could
probably use nng and the new polyamorous mode for the pairv1 protocol.
Finally you could just open separate sockets for each client but then you
have to keep track of them so that might not be practical.

Actually you might want to check out the surveyor pattern.

**Comment by douglascordeiro** [comment]
Keep a track on each client is not a issue for me, I would need to do this anyway as this system will work with subscribe. But How I get pipe id in order to do the association and then call the send for a specific pipe?

**Comment by gdamore** [comment]
Thinking about this some more, I think raw mode with “long polling” might
be the right answer.  Its a PITA, and will complicate your server design
somewhat, but I can’t think of anything else that is both easy to do, and
available in nanomsg.   If you use nng there are a number of other options
you can explore, since then we have pipe IDs that are available, although
even then some functionality (planned) is missing from nng.  (Basically you
need a pipe connection establishment callback so you can pick up the pipe
id without having to receive a message to get it.)

 - Garrett

**Comment by gdamore** [comment]
This was a question, not really a bug or request for new functionality.
