### ISSUE TITLE
Handle leak on Windows

### ISSUE THREAD

**Issue by Framnk** [nanomsg/nanomsg#948]
Hi, 

I've found that simply calling:
```
 int socket = nn_socket(AF_SP, NN_REQ);
nn_close(socket);
```
In a loop will show an ever increasing use of handle resources on Windows (until the process eventually terminates due to no more handles available).

**Comment by gdamore** [comment]
I will have to look at this later.  I'm pretty sure that the new library, libnng, does not suffer from this.

**Comment by gdamore** [comment]
So I'm looking at the code, and not spotting anything.  I'll have to debug this at run time.

One thing that stands out is that the eventfd logic in legacy libnanomsg is kind of silly, requiring a global lock on a well-known low-numbered port to set things up.  In libnng we used a different approach.  I'll note that in a separate bug.

**Comment by gdamore** [comment]
WIth the integration of 19e01dcaf1afda031143ae171d8eeadd0c49fee1 it's likely that this was fixed.  Submitter, can you please double check.

**Comment by gdamore** [comment]
Good catch.  This only affects windows because other platforms don't have to allocate resources to create a semaphore.  One of these days I'll figure out how to properly catch this kind of thing on Windows (meaning I need to learn to use the capabilities present in Visual Studio I guess -- or figure out how to get the sanitizers working on Windows.)
