### ISSUE TITLE
Big messages (> ~800 kb) transmission problem

### ISSUE THREAD

**Issue by arencour** [nanomsg/nanomsg#951]
Hello! We try to use ipc transport for transmission big data (e.g. 2 display full-screen screenshot). If message size more then ~800 kB (by experience) trnsmission does not finish successfully. Message was sent from source, but not received by destination, next messages unable to send.

**Comment by gdamore** [comment]
The problem here is likely the NN_RCVMAXSIZE option needs to be set -- it defaults to 1MB, and nanomsg will reject messages larger than.  You can set this option with nn_setsockopt(), and if you set it to 0 then messages of any size will be accepted.

(The reason for this option to exist is to prevent denial of service caused by remote parties... they could for example ask for a 2GB file, and nanomsg would try to allocate that RAM to hold the incoming message.  They don't even have to send the actual data at that point, making a DoS attack pretty easy without this kind of protection in place.)
