### ISSUE TITLE
Android NDK support

### ISSUE THREAD

**Issue by RobotixDK** [nanomsg/nanomsg#958]
When trying to build using the Android NDK, i get this warning:

-- OS System is Android
-- OS Version is 1
CMake Warning (dev) at CMakeLists.txt:140 (message):
  WARNING: This platform may or may not be supported: Android
This warning is for project developers.  Use -Wno-dev to suppress it.

And it wont compile:
In file included from /Users/dk8rabro/Documents/git/LPFPlatform/3rdParty/nanomsg-1.1.2/src/core/ep.c:28:
/Users/dk8rabro/Documents/git/LPFPlatform/3rdParty/nanomsg-1.1.2/src/core/sock.h:59:19: error: field has incomplete type 'struct nn_sem'
    struct nn_sem termsem;

Any plans for Android support?

**Comment by gdamore** [comment]
You might want to give libnng a crack.  I *suspect* it may work more easily.  See github.com/nanomsg/nng -- yes its pre-release, but I'm quickly pushing towards a 1.0 release.

Now having said that, you *should* have pthread support on Android, so probably something just needs to be done to help ensure that the software can see it.  What may be necessary is to make the Android CMake stuff behave like Linux.  (-DNN_HAVE_LINUX).   My guess is that if you can arrange -DNN_HAVE_LINUX then it will all "just work".

**Comment by gdamore** [comment]
Ok, reading the NDK, it's just Linux with an abbreviated set of compatible libraries, and a custom libc (bionic).  The libc appears to support the necessary things we need, including pthreads APIs, epoll, and eventfd.  So it really should just be a matter of duplicating the Linux logic in the CMakeLists.txt to apply to Android as well.

I don't have an NDK handy to validate this with, but if you are able to do so, I'd be happy to accept a PR.

**Comment by RobotixDK** [comment]
Hi, thanks for the replies. However setting NN_HAVE_LINUX for Android
didn't do the trick.

This NNG, will it be nanomsg compliant? And do you know if anyone's looking
into Unity/c# support here?

2018-03-16 21:53 GMT+01:00 gdamore <notifications@github.com>:

**Comment by gdamore** [comment]
I wonder why that didn't work with Android.  I wonder if the CMakeLists checks (which include linking against -lpthread, which appears not to be supported in modern NDK) are somehow breaking.  One idea might be to add a check for nn_check_lib(c sem_wait NN_HAVE_SEMAPHORE_C), and then add that case for the add_definitions (-DNN_HAVE_SEMAPHORE) check below.

Essentially I think you need -DNN_HAVE_SEMAPHORE

With respect to NNG, NNG is quite compatible with nanomsg. 

It offers:

a) Wire compatibility.  Every protocol that nanomsg supports, NNG does.
b) API compatibility.  Every (or nearly so!) nanomsg application should be able to be compiled against libnng, only adjusting the include location and link library.
c) ABI compatibility (some platforms).  On some systems, its possible merely *relink* a legacy nanomsg app against -lnng instead of -lnanomsg (e.g. via LD_PRELOAD).

**Comment by gdamore** [comment]
I'm not familiar with Unity, but I know that there is a .net effort in progress.

**Comment by gdamore** [comment]
I can probably knock this out today if there is need (meaning if you still want old nanomsg instead of NNG.)

**Comment by RobotixDK** [comment]
We parked the idea of using nanomsg or nng, due to lack of crossplatform Unity support. So currently using ZMQ.

Thanks,
Rasmus 

Sendt fra min iPhone

**Comment by gdamore** [comment]
As I'm already doing a release for 1.1.4 to address a new bug, I'll probably roll this into that release.
